# @(#)88	1.9  src/tenplus/lib/util/Makefile, tenplus, tenplus411, GOLD410 6/9/93 11:30:08
#
# COMPONENT_NAME: (INED) INed Editor
# 
# ORIGINS:  9, 10, 27
# 
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
# 
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.


INCFLAGS = -I${MAKETOP}/tenplus/include
LIBRARIES = libutil.a 
OFILES = a2string.o	attr_util.o	mb_util.o	dispwidth.o catscan.o    \
	nls_path.o Lgetregion.o	Llock.o	Lputregion.o abspath.o           \
	backname.o fakename.o	findfile.o ghost.o gmatch.o	makestring.o	 \
	modebits.o p2string.o	packup.o pathcat.o s2pointer.o             \
	smear.o	treecopy.o uniqname.o	unpackup.o 

.include <${RULES_MK}>
