/*LINTLIBRARY*/
#if !defined(lint)
static char sccsid[] = "@(#)86	1.5  src/tenplus/lib/util/uniqname.c, tenplus, tenplus411, GOLD410 7/18/91 13:48:53";
#endif /* lint */

/*
 * COMPONENT_NAME: (INED) INed Editor
 *
 * FUNCTIONS:	uniqname
 * 
 * ORIGINS:  9, 10
 * 
 * This module contains IBM CONFIDENTIAL code. -- (IBM
 * Confidential Restricted when combined with the aggregated
 * modules for this product)                  SOURCE MATERIALS
 * (C) COPYRIGHT International Business Machines Corp. 1985, 1988
 * All Rights Reserved
 * 
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */
 
#include <unistd.h>
#include <stdio.h>
#include <limits.h>
#include <database.h>
#include <fcntl.h>
#include <libobj.h>

/****************************************************************************/
/* uniqname: generate unique temporary file name                            */
/*                                                                          */
/* arguments:              int flag - whether to pre-increment counter      */
/*                                                                          */
/* return value:           char *   - the unique temporary name             */
/*                                                                          */
/* globals referenced:     none                                             */
/*                                                                          */
/* globals changed:        none                                             */
/*                                                                          */
/* synopsis:                                                                */
/*     uniqname returns a unique temporary file name of the form            */
/*     /tmp/<pid>t<num>, where <pid> is the process id and <num>            */
/*     is a unique number generated by a static counter.                    */
/*                                                                          */
/*     If the given flag is TRUE, the counter is incremented before         */
/*     going into the filename, and continues to be incremented until       */
/*     reaching a filename that does not exist.                             */
/*                                                                          */
/*     If the given flag is FALSE, the counter is not incremented           */
/*     and the non-incremented filename MUST ! EXIST ALREADY!             */
/*     The non-incremented filename is returned.                            */
/****************************************************************************/

char *uniqname (int flag)
    {
    static char name [30 * MB_LEN_MAX];
    static _pid;
    static _ucnt;
    if (_pid ==	0)
	_pid = getpid ();

    do
	{
	(void) sprintf (name, "/tmp/%dt%d", _pid, flag ? ++_ucnt : _ucnt);
	}
	while (flag && fexists (name));

    return (name);
    }

