# @(#)46        1.1  src/bos/usr/samples/ndd/Makefile, entsamp, bos411, 9428A410j 1/14/94 13:43:16
#
# COMPONENT_NAME: ENTSAMP
#
# FUNCTIONS: Makefile for CDLI Device Driver samples
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES               = entsamp.h entsamp_mac.h entsamp_pio.h \
			entsamp_hw.h entsamp_errids.h entsamp_cfg.c \
			entsamp_open.c entsamp_out.c entsamp_close.c \
			entsamp_ctl.c entsamp_intr.c entsamp_err.c \
			entsamp_util.c

ILIST                   = ${DATAFILES}
IDIR                    = /usr/samples/ndd/

.include <${RULES_MK}>
