# @(#)80        1.1  src/bos/usr/sbin/ndb/Makefile, cmdnet, bos411, 9428A410j 8/5/92 17:48:03
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= ndb
MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}

ILIST		= ndb
IDIR		= /usr/sbin/

LIBS		= -lunpack

.include <${RULES_MK}>
