# @(#)70        1.1  src/rspc/usr/lib/boot/protoext/cd.proto.ext.sys.pci.rte.S, bosboot, rspc411, GOLD410 6/27/94 19:04:23
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.sys.pci.rte
#
cfgbus_pci ---- 777 0 0 /usr/lib/methods/cfgbus_pci
rspcios    ---- 777 0 0 /usr/lib/drivers/isa/rspcios 
