# @(#)97        1.1  src/rspc/usr/lib/boot/protoext/disk.proto.ext.ide.disk.rte.S, bosboot, rspc41J, 9510A 2/17/95 17:12:18
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.ide.disk.rte
#
cfgidedisk	---- 777 0 0 /usr/lib/methods/cfgidedisk
idedisk		---- 777 0 0 /usr/lib/drivers/idedisk
idediskpin	---- 777 0 0 /usr/lib/drivers/idediskpin
