# @(#)72        1.1  src/rspc/usr/lib/boot/protoext/disk.proto.ext.pci.00100100.rte.S, bosboot, rspc411, GOLD410 6/27/94 19:04:57
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.pci.00100100.rte
cfgncr_scsi    ---- 777 0 0 /usr/lib/methods/cfgncr_scsi
ncr810dd  ---- 777 0 0 /usr/lib/drivers/pci/ncr810dd
