# @(#)98        1.1  src/rspc/usr/lib/boot/protoext/disk.proto.ext.isa_sio.PNP0600.rte.S, bosboot, rspc41J, 9510A 2/17/95 17:12:24
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.isa_sio.PNP0600.rte
#
cfgataide	---- 777 0 0 /usr/lib/methods/cfgataide
ataide		---- 777 0 0 /usr/lib/drivers/ataide
ataidepin	---- 777 0 0 /usr/lib/drivers/ataidepin
