# @(#)11        1.4  src/rspc/usr/lib/boot/protoext/ent.proto.ext.isa.ethernet.rte.S, bosboot, rspc41J, 9513A_all 3/28/95 15:22:35
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.isa.ethernet.rte
#
eth_demux ---- 777 0 0 /usr/lib/drivers/eth_demux
ientdd ---- 777 0 0 /usr/lib/drivers/isa/ientdd
cfgdmxeth ---- 777 0 0 /usr/lib/methods/cfgdmxeth
cfgisaent ---- 777 0 0 /usr/lib/methods/cfgisaent
ucfgent ---- 777 0 0 /usr/lib/methods/ucfgent
