# @(#)46        1.1  src/rspc/usr/lib/boot/protoext/ent.proto.ext.pci.22100020.rte.S, bosboot, rspc41J, 9516A_all 4/18/95 16:50:26
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME:  devices.pci.22100020.rte
#
cfgkent ---- 777 0 0 /usr/lib/methods/cfgkent
kentdd  ---- 777 0 0 /usr/lib/drivers/pci/kentdd
