# @(#)76        1.1  src/rspc/usr/lib/boot/protoext/ent.proto.ext.pci.86808404.rte.S, bosboot, rspc411, GOLD410 6/27/94 19:05:56
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.pci.86808404.rte
#
cfgbus_isa ---- 777 0 0 /usr/lib/methods/cfgbus_isa
