# @(#)65	1.6  src/rspc/usr/lib/boot/protoext/Makefile, bosboot, rspc41J, 9516A_all 4/18/95 16:48:30
#
# COMPONENT_NAME: rspccfg
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS = \
	rspc.pcfg \
	cd.proto.ext.ide.cdrom.rte \
	cd.proto.ext.isa_sio.PNP0600.rte \
	cd.proto.ext.isa.sio.rte \
	cd.proto.ext.pci.00100100.rte \
	cd.proto.ext.pci.86808404.rte \
	cd.proto.ext.sys.pci.rte \
	disk.proto.ext.ide.disk.rte \
	disk.proto.ext.isa_sio.PNP0600.rte \
	disk.proto.ext.isa.sio.rte \
	disk.proto.ext.pci.00100100.rte \
	disk.proto.ext.pci.86808404.rte \
	disk.proto.ext.sys.pci.rte \
	ent.proto.ext.isa.ethernet.rte \
	ent.proto.ext.isa.sio.rte \
	ent.proto.ext.pci.22100020.rte \
	ent.proto.ext.pci.86808404.rte \
	ent.proto.ext.sys.pci.rte \
	tok.proto.ext.isa.tokenring.rte \
	tok.proto.ext.isa.sio.rte \
	tok.proto.ext.pci.14101800.rte \
	tok.proto.ext.pci.86808404.rte \
	tok.proto.ext.sys.pci.rte


ILIST		= ${SCRIPTS}

IDIR = /usr/lib/boot/protoext/

.include <${RULES_MK}>
