# @(#)12        1.4  src/rspc/usr/lib/boot/protoext/tok.proto.ext.isa.tokenring.rte.S, bosboot, rspc41J, 9513A_all 3/28/95 15:22:52
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.isa.tokenring.rte
#
tok_demux ---- 777 0 0 /usr/lib/drivers/tok_demux
itokdd ---- 777 0 0 /usr/lib/drivers/isa/itokdd
cfgdmxtok ---- 777 0 0 /usr/lib/methods/cfgdmxtok
cfgisatok ---- 777 0 0 /usr/lib/methods/cfgisatok
ucfgtok ---- 777 0 0 /usr/lib/methods/ucfgtok
