# 
# 
#
# ORIGINS: 27 
#
#
# 
.include	<${MAKETOP}nfs/NFS.mk>

VPATH		= ${MAKETOP}/bos/usr/include/rpc

DATAFILES       = \
        auth.h          \
        auth_des.h      \
        auth_unix.h     \
        clnt.h          \
        key_prot.h      \
        pmap_clnt.h     \
        pmap_prot.h     \
        pmap_rmt.h      \
        rpc.h           \
        rpc_msg.h       \
        svc.h           \
        svc_auth.h      \
        types.h         \
        xdr.h

INCLUDES        = ${DATAFILES}

IDIR		= /kernel/include/rpc/

.include <${RULES_MK}>
