#
#
#
#   ORIGINS: 27
#
#
#

IDIR                    = /usr/sbin/perf/diag_tool/
ILIST                   = \
Driver_ gettime_ processes_ vmm_ workload_ \
cpu_ lsattr_ pv_ workload.1_ \
err_ mem_ report_ workload.2_ \
fn_ network_ retention_ workload.3_ \
fs_ paging_ uptime_ workload.4_ \
pdt_report pdt_config .40kFile .collection.control .files \
.reporting.control .retention.control .retention.list .thresholds \
.reporting.list \
report getvmparms getschedparms

.40kFile_IDIR = /var/perf/dat/diag_tool/
.collection.control_IDIR = /var/perf/cfg/diag_tool/
.filles_IDIR = /var/perf/cfg/diag_tool/
.reporting.control_IDIR = /var/perf/cfg/diag_tool/
.retention.control_IDIR = /var/perf/cfg/diag_tool/
.retention.list_IDIR = /var/perf/cfg/diag_tool/
.reporting.list_IDIR = /var/perf/cfg/diag_tool/
.thresholds_IDIR = /var/perf/cfg/diag_tool/


OTHERS=

OTHERS+=report
report:report.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=getvmparms
getvmparms:getvmparms.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=getschedparms
getschedparms:getschedparms.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=Driver_
Driver_:Driver_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=gettime_
gettime_:gettime_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=processes_
processes_:processes_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=vmm_
vmm_:vmm_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=workload_
workload_:workload_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=cpu_
cpu_:cpu_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=lsattr_
lsattr_:lsattr_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=pv_
pv_:pv_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=workload.1_
workload.1_:workload.1_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=err_
err_:err_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=mem_
mem_:mem_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=report_
report_:report_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=workload.2_
workload.2_:workload.2_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=fn_
fn_:fn_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=network_
network_:network_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=retention_
retention_:retention_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=workload.3_
workload.3_:workload.3_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=fs_
fs_:fs_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=paging_
paging_:paging_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=uptime_
uptime_:uptime_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=workload.4_
workload.4_:workload.4_.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=pdt_report
pdt_report:pdt_report.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=pdt_config
pdt_config:pdt_config.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.40kFile
.40kFile:.40kFile.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.collection.control
.collection.control:.collection.control.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.files
.files:.files.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.reporting.control
.reporting.control:.reporting.control.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.retention.control
.retention.control:.retention.control.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.retention.list
.retention.list:.retention.list.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.thresholds
.thresholds:.thresholds.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=.reporting.list
.reporting.list:.reporting.list.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

.include <${RULES_MK}>
