# @(#)92        1.1  src/bos/usr/sbin/bosboot/Makefile, bosboot, bos411, 9428A410j 9/1/92 10:20:35
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= bosboot
CATFILES	= bosboot.cat

ILIST		= ${SCRIPTS}

IDIR		= /usr/sbin/

.include <${RULES_MK}>

bosboot:	bosboot.cat
