# @(#)51	1.1  src/msg/bos/Makefile, bosmsg, msg411, GOLD410 2/9/94 08:44:53
#
# COMPONENT_NAME: bosmsg
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS	=	          \
          En_US De_DE Es_ES Fr_FR It_IT Nl_BE No_NO Sv_SE

.include <${RULES_MK}>
