# @(#)82        1.1  src/bos/usr/sbin/XNSrouted/tools/Makefile, Makefiles, bos411, 9428A410j 8/5/92 17:48:40
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= XNSquery
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= XNSquery
IDIR		= /usr/sbin/

CFLAGS		= -D_BSD=44 -DMAXLOGINS=16

OFILES		= xnsquery.o

.include <${RULES_MK}>
