# @(#)87	1.2  src/bos/usr/sbin/cron/at.deny.S, cmdcntl, bos411, 9428A410j 4/25/91 17:17:08
#
# COMPONENT_NAME: (CMDCNTL) system control commands
#
# FUNCTIONS:
#
# ORIGINS: 18, 27
#
# (C) COPYRIGHT International Business Machines Corp. 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# @OSF_COPYRIGHT@
#




