# @(#)90	1.2  src/bos/usr/sbin/cron/log.S, cmdcntl, bos411, 9428A410j 4/25/91 17:17:16
#
# COMPONENT_NAME: (CMDCNTL) commands needed for basic system needs
#
# FUNCTIONS: 
#
# ORIGINS: 27, 18
#
# (C) COPYRIGHT International Business Machines Corp. 1989,1991
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


