# @(#)55  1.2  src/bos/usr/sbin/nddstat/entstat/Makefile, nddstat, bos411, 9428A410j 2/24/94 15:01:49 
#
#   COMPONENT_NAME: NDDSTAT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1989,1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
VPATH		= ../common

PROGRAMS	= entstat
MSGHDRS         = entstat_msg.h
CATFILES        = entstat.cat
HFILES          = ${MSGHDRS}

ILIST		= entstat
IDIR		= /usr/sbin/

OFILES		= main.o entstat.o

.include <${RULES_MK}>
