$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)90	1.1  src/msg/bos/base/auditstm.msg, bosmsg, msg411, GOLD410 2/9/94 08:46:46
$
$ COMPONENT_NAME: (CMDSAUD) security: auditing subsystem
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989-1991
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$                                                                  

$
$
$ messages for auditstream
$

$set MS_AUDITSTM

$quote "

USAGE		"Usage: auditstream [-c class[,class]*]"
ERRPRIV		"** SET_PROC_AUDIT privilege required"
ERRSUSPEND      "** cannot suspend auditing"
