$ ENGLISH_SOURCE_VERSION= 1.7
$ @(#)94	1.1  src/msg/bos/base/banner.msg, bosmsg, msg411, GOLD410 2/9/94 08:46:58
$
$ COMPONENT_NAME: (CMDMISC) miscellaneous commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1985, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$set MS_BANNER
$quote '

USAGE 'Usage: banner String\n\
\tMaximum 10 characters per line and 10 lines.\n\
\tWrites characters in large letters to standard output.\n'
KJISTR 'banner: 0702-050 This command only supports ASCII characters.\n'
