$ ENGLISH_SOURCE_VERSION= 1.2.1.6
$ @(#)07  1.3  src/msg/bos/base/bootinfo.msg, bosmsg, msg411, 9430C411a 7/23/94 12:20:02
$
$ COMPONENT_NAME: (BOSBOOT) Base Operating System Boot
$
$ FUNCTIONS:  bootinfo.msg
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1994
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "

$set 250

1 "\nusage: bootinfo [ -P psize -s disk ] |-b |-B disk |-c |\n"
2 "\t\t-k |-m |-q adapter |-r |-t |-T |-o disk |-z\n"
$ Do not translate bootinfo
$ Deleted messages 3 - 20
21 "\n 0301-268 Object Data Manager initialize failed!\n"
$ Object Data Manager (ODM) is an AIX specific facility intended
$  for storing system information.
$ Deleted message 22
$ End of bootinfo.msg
