$ ENGLISH_SOURCE_VERSION= 1.4
$ @(#)14	1.1  src/msg/bos/base/calendar.msg, bosmsg, msg411, GOLD410 2/9/94 08:47:57
$
$ COMPONENT_NAME: (CMDMISC) miscellaneous commands 
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$set MS_CALENDAR
$quote "
$ 
ENOEXIST	"%s: %s/calendar not found\n"
$ Do not translate %s/calendar.  It is the file name.
MAILSUBJ	"Subject: Calendar for %s\n"
NOTFILE		"%s: %s/calendar is a directory rather than a file\n"
USAGE		"Usage: calendar [-]"
