$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)16  1.1  src/msg/bos/base/canonls.msg, bosmsg, msg411, GOLD410 2/9/94 08:48:04
$
$ COMPONENT_NAME: CMDTEXT
$
$ FUNCTIONS:
$
$ ORIGINS: 27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ messages for canonls
$
$quote "         define quote character.
$len 
$set MS_canonls        Define initial set#
M_MSG_61    "canonls: Point size set to %d.\n"
M_MSG_62	"canonls: 1006-401 %d byte characters are not supported\n"
M_MSG_INVALID_LOCALE "canonls: 1006-402 Invalid locale %s. It is changed to C.\n"
M_MSG_INVALID_FONT "canonls: 1006-403 Invalid font: %s\n"
M_MSG_DEFAULT_FONT "canonls: 1006-404 Default font %s is selected\n"
M_MSG_ICONV_NOT_FOUND "canonls: 1006-405 Code set converter from %s to %s not found.\n"
M_MSG_INVALID_FONT_FILE "canonls: 1006-406 Invalid font file: %s\n"
