$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)19   1.1  src/msg/bos/base/ciedd.msg, bosmsg, msg411, 9430C411a 7/23/94 12:20:17
$
$  COMPONENT_NAME: SYSXCIE
$
$  FUNCTIONS: Device configuration message catalog
$
$  ORIGINS: 27
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1992
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$  COMIO Emulator
$set 1
1  "Receive Queue Size (Frames)"
2  "Status Queue Size (Events)"
3  "Pass Beacon Frames"
4  "Pass NSA Frames"
5  "Pass SMT Frames"
6  "802.3 ETHERTYPE Field Offset"
7  "Standard ETHERTYPE Field Offset"
