$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)48        1.1  src/msg/bos/base/cksum.msg, bosmsg, msg411, GOLD410 2/9/94 08:49:43
$
$ COMPONENT_NAME: (CMDPOSIX) Commands required by Posix 1003.2
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1990, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ messages for command head
$
$quote "         define quote character.
$len
$set MS_CKSUM        Define initial set#
USAGE		"Usage: cksum [File ...]\n"
$ Do not translate cksum.
