$ ENGLISH_SOURCE_VERSION= 1.2
$  @(#)49  1.1  src/msg/bos/base/ckwinsiz.msg, bosmsg, msg411, GOLD410 2/9/94 08:49:46
$ 
$    COMPONENT_NAME: RCS
$ 
$    FUNCTIONS: none
$ 
$    ORIGINS: 27
$ 
$    IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$    combined with the aggregated modules for this product)
$                     SOURCE MATERIALS
$ 
$    (C) COPYRIGHT International Business Machines Corp. 1993
$    All Rights Reserved
$    US Government Users Restricted Rights - Use, duplication or
$    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$   

$ scmc msg file created Fri Apr 30 14:37:51 1993
$ user:  elaird

$quote "         define quote character.

$ scmc msg file created Wed Apr 28 18:12:14 1993 
$ user:  root 
$len 
$set MS_ckwinsiz        Define initial set#

M_MSG_1             "Error retrieving window size.\n"
M_MSG_2             "\nA minimum window size of 80 \n\
by 24 is required to run this program.\n\
Please check your terminal type or \n\
window size and try again.\n"
