$ ENGLISH_SOURCE_VERSION= 1.1

$ @(#)54 1.1  src/msg/bos/base/cmdcomm.msg, bosmsg, msg411, GOLD410 2/9/94 08:50:00

$
$ COMPONENT_NAME:  (CMDCOMM) cmdcomm.msg
$
$ FUNCTIONS: (none)
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$set 23
$quote "

15 "Broadcast Message to all Users"
20 "MESSAGE"
