$ ENGLISH_SOURCE_VERSION= 1.2

$ @(#)59 1.1  src/msg/bos/base/cmdiconv.msg, bosmsg, msg411, GOLD410 2/9/94 08:50:16

$
$ COMPONENT_NAME:  (CMDICONV) cmdiconv.msg
$
$ FUNCTIONS: (none)
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$set 43
$quote "

10 "Convert Flat File"
20 "CURRENT FILE / DIRECTORY name"
30 "CURRENT CODE set"
40 "NEW FILE / DIRECTORY name"
50 "NEW CODE set"

