$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)62	1.2  src/msg/bos/base/cmdlice.msg, bosmsg, msg411, 9430C411a 7/23/94 12:20:52
$ ****************************************************************************\
$ COMPONENT_NAME: CMDLICENSE (Smit dialog message source)
$
$ FUNCTIONS: none
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1994
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ ****************************************************************************/
$
$
$quote "
$set 29
1 "Change / Show Number of Licensed Users"
2 "Maximum number of FIXED licenses"
3 "FLOATING licensing"
4 "on,off"
$  ***  There are 2 types of user licensing: fixed and floating.  ***
$  ***  Fixed licensing is always enabled.  Floating licensing    ***
$  ***  can be enabled or disabled (on or off).                   ***

