$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)72	1.1  src/msg/bos/base/cmdsrc.msg, bosmsg, msg411, GOLD410 2/9/94 08:51:03
$
$ COMPONENT_NAME: (cmdsrc) System Resource Controller
$
$ FUNCTIONS:
$       none
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregate modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$              src.msg

$quote "         define quote character.

$set 40
1 "List All Subsystems"
2 "Query TYPE"
3 "Query a Subserver"
4 "Query a Subsystem"
5 "Refresh a Subsystem"
7 "SUBSERVER name"
8 "Start Trace"
9 "Start a Subserver"
10 "Start a Subsystem"
12 "Stop All Subsystems"
13 "Stop Subsystem"
14 "Stop TYPE"
15 "Stop Trace"
16 "Stop a Subserver"
17 "Stop a Subsystem"
18 "Subserver name"
19 "Subservers"
20 "Subsystem Name"
21 "Subsystem PROCESS ID"
22 "Subsystems"
23 "Trace Subserver"
24 "Trace Subsystem"
25 "Trace TYPE"
