$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)11        1.3 7/23/94 src/msg/bos/base/devices_p.msg, bosmsg, msg411, 9430C411a 12:22:59
$
$  COMPONENT_NAME: (CFGMETHODS) device configuration methods
$ 
$  FUNCTIONS: Devices configuration message catalog
$ 
$  ORIGINS: 83
$ 
$  LEVEL 1, 5 Years Bull Confidential Information
$ 
$ 
$ System Object and related devices
$quote "
$set 1
1 "Cabinet"
2 "Operator Panel"
3 "Power Supply"
4 "Power Supply Interface"
$
$ Family 2 bus
$set 3
1 "MCA Planar"
