$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)56        1.1  src/msg/bos/base/dirname.msg, bosmsg, msg411, GOLD410 2/9/94 08:56:17
$
$ COMPONENT_NAME: (CMDSH) Bourne shell and related commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1992
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$set MS_DIRNAME

USAGE "Usage: dirname String\n"
$ Do not translate dirname.
