$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)25\t1.1  src/msg/bos/base/dscreen.msg, bosmsg, msg411, 9430C411a 7/23/94 12:23:29
$
$ COMPONENT_NAME: (cmdtty) terminal control command
$
$ FUNCTIONS:
$
$ ORIGINS: 80
$
$ This software contains proprietary and confidential information of Digi
$ International Inc.  By accepting transfer of this copy, Recipient agrees
$ to retain this software in confidence, to prevent disclosure to others, and
$ to make no use of this software other than that for which it was delivered.
$ This is an unpublished copyright work Digi International Inc.  Execpt as
$ permitted by federal law, 17 USC 117, copying is strictly prohibited.
$
$ Digi International Inc. CONFIDENTIAL - (Digi International Inc. Confidential
$ when combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT Digi International Inc. 1988-1992
$ All Rights Reserved
$
$ US Government Users Restircted Rights - Use, duplication or disclosure
$ restricted by GSA ADP Schedule Contract with Digi International Inc.
$

$
$ messages for command sysline
$

$set MS_DSCREEN

$quote "

DUMMY	"howdy"
