$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)59        1.2  src/msg/bos/base/dtsmit.msg, bosmsg, msg411, 9435A411a 8/25/94 16:04:40
$
$   COMPONENT_NAME: Desktop
$
$   FUNCTIONS: none
$
$   ORIGINS: 27
$
$
$   (C) COPYRIGHT International Business Machines Corp. 1994
$   All Rights Reserved
$   Licensed Materials - Property of IBM
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "         define quote character.

$set 30
1 "Change System User Interface  \n"

$set 40
1 "Select System User Interface  \n"

$set 50
1 "Select System Login User Interface  \n"
