$ ENGLISH_SOURCE_VERSION= 1.4
$ @(#)09	1.1  src/msg/bos/base/from.msg, bosmsg, msg411, GOLD410 2/9/94 08:59:01
$ 
$ COMPONENT_NAME: CMDMAILX from.msg
$ 
$ FUNCTIONS: 
$
$ ORIGINS: 10  26  27 
$
$ (C) COPYRIGHT International Business Machines Corp. 1985, 1989
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ scmc msg file created Thu Jul 13 16:53:07 1989
$ user:  jeffe

$quote "         define quote character.

$len 
$set MS_from        Define initial set#

M_MSG_1              "Usage: from [-d directory] [-s sender] [user]\n"
M_MSG_2              "Cannot get your login name\n"
M_MSG_3              "Cannot open %s's mailbox\n"
