$ ENGLISH_SOURCE_VERSION= 1.3.1.2
$ @(#)18	1.1  src/msg/bos/base/genxlt.msg, bosmsg, msg411, GOLD410 2/9/94 08:59:31
$
$   COMPONENT_NAME: CMDICONV
$
$   FUNCTIONS: none
$
$   ORIGINS: 27
$
$   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$   combined with the aggregated modules for this product)
$                    SOURCE MATERIALS
$
$   (C) COPYRIGHT International Business Machines Corp. 1991, 1993
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote	"		define quote character.
$set	MS_genxlt	Define initial set#

M_MSG_1		"Usage: genxlt [target]\n"
M_MSG_2		"genxlt: 0791-101 Unable to open target file.\n"
M_MSG_3		"genxlt: 0791-102 There was no assignment for index %d.\n"
M_MSG_4		"genxlt: 0791-103 Unable to write for target file.\n"
M_MSG_5		"genxlt: 0791-104 Invalid format at line %d.\n"
M_MSG_6		"genxlt: 0791-105 No substitution character is defined.\n"
M_MSG_7		"genxlt: 0791-106 Not enough memory.\n"
