$ ENGLISH_SOURCE_VERSION= 1.6
$ @(#)27	1.1  src/msg/bos/base/greek.msg, bosmsg, msg411, GOLD410 2/9/94 09:00:04
$
$ COMPONENT_NAME: (CMDTEXT) Text Formatting
$
$ FUNCTIONS: greek.msg
$
$ ORIGINS: 3,27,28
$
$ This module contains IBM CONFIDENTIAL code. -- (IBM
$ Confidential Restricted when combined with the aggregated
$ modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ messages for greek 
$

$set MS_GREEK
$ Do not translate output formats used with C programs such as:
$ 	%d %i %x %X %u %c %s %f %e %E %g %G %p %n %ld
$ Do not translate shell variables such as:
$ 	$# $? $$ $! $- {$0 $1 $2 .... $some number}
$quote "
$ messages for greek.sh


1  "Usage: greek [ -TTerminal ]\n"
2  "greek: 1005-602 The %s is not implemented.\n"
