$ ENGLISH_SOURCE_VERSION= 1.6
$ @(#)30	1.1  src/msg/bos/base/groups.msg, bosmsg, msg411, GOLD410 2/9/94 09:00:10
$
$ COMPONENT_NAME: (CMDSAUTH) security: authentication functions
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "         define quote character.
$set MS_groups        Define initial set#

M_MSG_3 "0481-005 The specified user is not known.\n\
\tCheck the /etc/passwd file for all known users.\n"
M_MSG_4 "0481-006 Could not get \"group\" information.\n"
M_USAGE "usage: groups [user]\n"
