$ ENGLISH_SOURCE_VERSION= 1.4
$ @(#)44        1.1 2/9/94 09:01:02
$
$ COMPONENT_NAME: CMDSCCS       source code control system
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "
$set 49
1 "Usage: delta [-gList] [-n][-p] [-rSID] [-s] [-m[MRList]] [-y[Comment]]\n\
\t[File ...|-]\n\
\tCreates a delta (an update) in a Source Code Control System (SCCS) file.\n"
