$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)42        1.1 2/9/94 09:00:57
$
$ COMPONENT_NAME: CMDSCCS       source code control system
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote #
$set 26
1 #Cannot open the specified file.\n\
Check path name and permissions.\n\
The file cannot be opened for reading.  Either it does not exist\n\
or the user does not have read permission.\n#
