$ ENGLISH_SOURCE_VERSION= 1.9.1.2
$ @(#)62\t1.1  src/msg/bos/base/head.msg, bosmsg, msg411, GOLD410 2/9/94 09:02:04
$
$ COMPONENT_NAME: (CMDSCAN) commands that scan files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ messages for command head
$
$quote "         define quote character.
$len
$set MS_HEAD        Define initial set#

BADNUM	"head: 0652-036 Specify a positive decimal number.\n"
USAGE	"Usage: head [-Count | -n Number | -c Number] [File...]\n"
$ Do not translate head.
$ 0652-88 thru 0652-98 are reserved for this command.
