$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)73  1.1  src/msg/bos/base/ibm5584.msg, bosmsg, msg411, GOLD410 2/9/94 09:02:44
$
$ COMPONENT_NAME: (CMDTEXT) Text Formatting Services
$
$ FUNCTIONS:
$
$ ORIGINS: 10,27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ messages for ibm5584
$
$quote "         define quote character.
$len 
$set MS_ibm5584        Define initial set#
M_MSG_61    "ibm5584: 1006-501 Point size set to %d. Point size should be set to one of these sizes 4,5,8,10,16, or 20.\n"
M_MSG_62	"ibm5584: 1006-502 %d byte characters are not supported\n"
