$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)74  1.1  src/msg/bos/base/ibm5585H-T.msg, bosmsg, msg411, GOLD410 2/9/94 09:02:48
$
$ COMPONENT_NAME: (CMDTEXT) Text Formatting Services
$
$ FUNCTIONS:
$
$ ORIGINS: 10,27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ messages for ibm5585H-T
$
$quote "         define quote character.
$len 
$set MS_ibm5585H_T        Define initial set#
M_MSG_61    "ibm5585H-T: 1006-601 Point size set to %d. Point size should be set to one of these sizes 4,5,8,10,16, or 20.\n"
M_MSG_62	"ibm5585H-T: 1006-602 %d byte characters are not supported\n"

