$ ENGLISH_SOURCE_VERSION= 1.5
$ @(#)06	1.1  src/msg/bos/base/lastcomm.msg, bosmsg, msg411, GOLD410 7/28/94 1.1
$
$ COMPONENT_NAME: (CMDSTAT) lastcomm
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ messages for lastcomm
$

$quote "
$set MS_LASTCOMM


READ "lastcomm: 0551-007 The read system call failed.\n"
$ Do not translate read

NOMEM "lastcomm: 0551-008 There is not enough memory available for a device table.\n"
