$ ENGLISH_SOURCE_VERSION= 1.2.1.1
$ @(#)29	1.1  src/msg/bos/base/locale.msg, bosmsg, msg411, GOLD410 2/9/94 09:05:45
$
$ COMPONENT_NAME: (CMDNLS)
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$set LOCALE

ERR_USAGE	"Usage: locale [-a | -m] | [[-ck] name ... ]\n"
ERR_KEYWORD	"locale: unrecognized keyword, '%s', in argument list.\n"

