$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)34	1.1  src/msg/bos/base/logname.msg, bosmsg, msg411, GOLD410 2/9/94 09:06:00
$
$   COMPONENT_NAME: CMDSAUTH
$
$   FUNCTIONS: 
$
$   ORIGINS: 27
$
$   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$   combined with the aggregated modules for this product)
$                    SOURCE MATERIALS
$
$   (C) COPYRIGHT International Business Machines Corp. 1993
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$set MS_LOGNAME
$quote "
M_LNFAIL  "3004-700 %s: getlogin failed\n"
