$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)37        1.1  src/msg/bos/base/lorder.msg, bosmsg, msg411, GOLD410 2/9/94 09:06:08
$ COMPONENT_NAME: CMDAOUT (lorder command)  
$  FUNCTIONS: none  
$  ORIGINS: 27  
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when  
$  combined with the aggregated modules for this product)  
$                   SOURCE MATERIALS  
$  (C) COPYRIGHT International Business Machines Corp. 1993
$  All Rights Reserved  
$  US Government Users Restricted Rights - Use, duplication or  
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.  
$quote "         define quote character.

$len 
$set MS_LORDER       Define initial set#

USAGE_MSG            "Usage: lorder file ...\n"
$ Do not translate command name (lorder) in USAGE_MSG  
