$ ENGLISH_SOURCE_VERSION= 1.6
$ @(#)68	1.1  src/msg/bos/base/mesg.msg, bosmsg, msg411, GOLD410 2/9/94 09:07:35
$
$ COMPONENT_NAME: (CMDCOMM) user to user communication
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989,1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$set MS_MESG
$quote "
CANTCHG "mesg: 0803-001 Cannot change the access to \"%s\"."
IS "The current status is %s.\n"
NOSTATUS "mesg: 0803-002 Cannot get the status of %s."
NOTERM "mesg: 0803-003 Cannot find the terminal."
USAGE "Usage: mesg [y|n]\n"
