$ ENGLISH_SOURCE_VERSION= 1.3.1.2
$ @(#)79        1.1  src/msg/bos/base/mkproto.msg, bosmsg, msg411, GOLD410 2/9/94 09:08:10
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files 
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 367 - 369 reserved for this file.
$
$set MS_MKPROTO
$ message for the mkproto.sh shell script

1 "Usage: mkproto Special Proto"
$ Do not translate mkproto.
$ Special can a block device name, raw device name or file system name.
$ Proto is the name of a prototype file.
