$ ENGLISH_SOURCE_VERSION= 1.5
$ @(#)82	1.1  src/msg/bos/base/mkstr.msg, bosmsg, msg411, GOLD410 2/9/94 09:08:17
$
$ COMPONENT_NAME: (CMDPROG) Programming Utilities
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1985, 1989
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ messages for mkstr
$

$len
$set MS_MKSTR

$quote "

USAGE "Usage: %s [-] MessageFile Prefix File ...\n"
