$ ENGLISH_SOURCE_VERSION= 1.5.1.2
$ @(#)96        1.1  src/msg/bos/base/mvdir.msg, bosmsg, msg411, GOLD410 2/9/94 09:08:57
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files      
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 380 - 384 reserved for this file.
$
$set MS_MVDIR

USAGE "Usage: mvdir Directory1 Directory2\n"
$ Do not translate mvdir.
