$ ENGLISH_SOURCE_VERSION= 1.10
$ @(#)11        1.1  src/msg/bos/base/nohup.msg, bosmsg, msg411, GOLD410 2/9/94 09:09:45
$
$ COMPONENT_NAME: (CMDCNTL) system control commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27, 18
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989,1992
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ (c) Copyright 1990 OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$ OSF/1 1.0
$
$quote "
$set MS_NOHUP
$ Do not translate nohup 


USAGE "Usage: nohup Command [ Argument... ]\n"
NOCREAT "nohup: 0509-019 Cannot open or create the nohup.out file.\n"
$ Do not translate nohup.out
SENDOUT "Sending nohup output to %s.\n"
