$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)59	1.1  src/msg/bos/base/notinet.msg, bosmsg, msg411, GOLD410 4/26/94 16:54:56
$
$   COMPONENT_NAME: tcpip
$
$   FUNCTIONS: none
$
$   ORIGINS: 27
$
$
$   (C) COPYRIGHT International Business Machines Corp. 1994
$   All Rights Reserved
$   Licensed Materials - Property of IBM
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ messages for notinet  
$
$ The range of message numbers assigned to this file are 181-186 
$quote "         define quote character.
$len 
$set MS_NOTINET        Define initial set#

$ Do not translate notinet:, %s 
ERR_FTOK             "%s: 0822-181 The shared memory system call ftok failed.\n"
$ Do not translate ftok 
$ share memory failure on ftok 
