$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)42	1.1  src/msg/bos/base/printinfo.msg, bosmsg, msg411, GOLD410 2/9/94 09:11:41
$
$  COMPONENT_NAME: LIBCURSES
$
$  FUNCTIONS:  Message Catalog
$
$  ORIGINS: 27
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1993
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "         define quote character.
$len 
$set MS_PRINTINFO        Define initial set#

$ This catalog uses messages in the range 1375-300 -- 1375-399.

ENDOFSTR "End of string variables.\n"

FLAGS "Boolean variables:\n"

NUMBERS "Numeric variables:\n"

STRINGS "String variables:\n"

TERMTYPE "The terminal type is %s.\n"

TOOLONG "1375-300 WARNING: The termcap entry is too long!\n"
$ Do not translate 'termcap'.

