$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)01	1.2  src/msg/bos/base/pwrcmd.msg, bosmsg, msg411, 9439A411a 9/26/94 15:23:18
$
$ COMPONENT_NAME: (PWRCMD) smit dialog message source
$
$ FUNCTIONS: Message catalog for PWRCMD smit messages
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1994
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ This is the message file for menus associated with software installation
$ and maintenance.  This set of menus interfaces to commands in the
$ cmdinstl component.
$
$quote "
$set 55
$
1	"Power Management"
2	"Enable/Disable Power Management"
3	"Enable/Disable Power Management"
4	"Enable or Disable Power Management"
5	"Request Power Management State Transition during PM Enable"
6	"Request Power Management State Transition during PM Enable"
7	"Request PM State Transition during PM Enable"
8	"Power Management Data of Entire System"
9	"Power Management Data of Entire System"
10	"Default Power Management State"
11	"System Idle Timer (sec.)"
12	"Action When System Idle Timer Expires"
13	"Action If Notebook Lid is Closed"
14	"Action When Main Power Switched Off"
15	"Action If Optional Battery is Low"
16	"Enable or Disable Beep for Power Management"
17	"Enable or Disable Resume Password"
18	"LFT session handling for Suspend/Hibernation"
19	"Power Management Data of a PM Aware Device"
20	"Power Management Data of a PM Aware Device"
21	"Device NAME"
22	"Power Management Data of a PM Aware Device"
23	"Device NAME"
24	"Device Idle Time"
25	"Battery"
26	"Show Battery Information"
27	"Start Battery Discharge"
28	"Show Battery Information"
29	"Start Battery Discharge"
