$ ENGLISH_SOURCE_VERSION= 1.4
$ @(#)83	1.1  src/msg/bos/base/rev.msg, bosmsg, msg411, GOLD410 2/9/94 09:14:12
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1985, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ messages for rev
$
$quote "
$
$ $ Message numbers 582 - 584 reserved for this file.
$
$set MS_REV
$ Do not translate rev.

OPENFAIL "rev: 0653-582 Cannot open file %s.\n"
$ %s is replaced by the name of the file that cannot be opened.
