$ ENGLISH_SOURCE_VERSION= 1.3
$  @(#)94  1.1  src/msg/bos/base/rmslip.msg, bosmsg, msg411, GOLD410 2/9/94 09:14:57
$ 
$    COMPONENT_NAME: RCS
$ 
$    FUNCTIONS: none
$ 
$    ORIGINS: 27
$ 
$    IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$    combined with the aggregated modules for this product)
$                     SOURCE MATERIALS
$ 
$    (C) COPYRIGHT International Business Machines Corp. 1993
$    All Rights Reserved
$    US Government Users Restricted Rights - Use, duplication or
$    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$   

$ scmc msg file created Sun May  2 14:07:41 1993
$ user:  elaird

$quote "         define quote character.

$len 
$set MS_rmslip        Define initial set#

M_MSG_1              "Usage: rmslip -n Connection_Name | rmslip  -a \n"
$ 
$  Don't translate the word rmslip (the command)
$ 
M_MSG_2              "This program needs at least one argument.\n"
M_MSG_4              "Unable to obtain a lock on the odm database.\n"
M_MSG_5              "Retrieval of error message failed.\n"
