$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)00	1.1  src/msg/bos/base/rpl.msg, bosmsg, msg411, GOLD410 2/9/94 09:15:17
$
$ COMPONENT_NAME: (INED) INed Editor
$ 
$ ORIGINS:  27
$ 
$ This module contains IBM CONFIDENTIAL code. -- (IBM
$ Confidential Restricted when combined with the aggregated
$ modules for this product)                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$quote "
$
$set MS_RPL 
$
$ Do not translate rpl
$
M_USAGE "Usage:  rpl Expression Substitute\n"
$ This message must end in \n.
$ On the altu edit screen, this will appear as '\n'.  If you then
$ display the source, you will see the '\n'
$
M_ILLPAT "rpl: 0611-287 The specified pattern is not a valid regular expression."
$
M_NULLPATTERN "rpl: 0611-288 The specified character pattern does not match any\n\
characters."
