$ ENGLISH_SOURCE_VERSION= 1.6
$ @(#)14        1.1 2/9/94 09:16:16
$
$ COMPONENT_NAME: CMDSCCS       source code control system
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "         define quote character.

$len 
$set 8        Define initial set#

NOTFOUND             "\n\
sccshelp: 1255-141 %s is not a valid parameter. (he1)\n"
$ Do not translate (he1). 
ARGTOOLNG            "\n\
sccshelp: 1255-142 Command parameter cannot exceed 50 characters. (he2)\n"
$ Do not translate (he2). 
MSGNOCMDNM           "Provide message number or command name.\n"
