$ ENGLISH_SOURCE_VERSION= 1.1.1.3
$ @(#)24	1.1  src/msg/bos/base/shell.msg, bosmsg, msg411, GOLD410 2/9/94 09:17:06
$ COMPONENT_NAME: (CMDSAUTH) security: user authentication
$
$ FUNCTIONS: none
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$set MS_SHELL

$
$ Messages for the SHELL command
$

$quote "

M_GETUSER	"3004-041 Cannot get user information for user name %s.\n"
M_SETPCRED	"3004-042 Cannot set credentials for %s.\n"
M_SETPENV	"3004-046 Cannot execute login shell for %s.\n"
M_GETTPATH	"3004-044 Cannot get trusted path information for user %s.\n"
M_NOTTY		"3004-045 Cannot get terminal port name.\n"
