$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)26	1.1  src/msg/bos/base/showstring.msg, bosmsg, msg411, GOLD410 2/9/94 09:17:17
$
$  COMPONENT_NAME: (LIBCURSE) Curses Library
$
$  FUNCTIONS:  none
$
$  ORIGINS: 27, 28
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1985, 1989
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "         define quote character.

$len 
$set MS_showstring        Define initial set#

DISPCOLS "_showstring: 1371-010 String must be less than %1$d characters wide.\
\n\t\tfirst %2$d, last %3$d, difference %4$d\n"
