$ ENGLISH_SOURCE_VERSION= 1.5
$  @(#)34  1.1  src/msg/bos/base/slipserver.msg, bosmsg, msg411, GOLD410 2/9/94 09:18:11
$ 
$    COMPONENT_NAME: RCS
$ 
$    FUNCTIONS: none
$ 
$    ORIGINS: 27
$ 
$    IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$    combined with the aggregated modules for this product)
$                     SOURCE MATERIALS
$ 
$    (C) COPYRIGHT International Business Machines Corp. 1993
$    All Rights Reserved
$    US Government Users Restricted Rights - Use, duplication or
$    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$   

$ scmc msg file created Sun May  2 19:01:56 1993
$ user:  root

$quote "         define quote character.

$len 
$set MS_slipserver        Define initial set#

M_MSG_1            "Unable to create a child process.\n"
M_MSG_2            "Multiple instances of the SLIP Connection Subsystem are not supported.\n"

