$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)39 1.1  src/msg/bos/base/sm_cmdps.msg, bosmsg, msg411, GOLD410 2/9/94 09:18:37

$
$ COMPONENT_NAME:  (CMDPS) cmdps.msg
$
$ FUNCTIONS: (none)
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1990
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$set 28
$quote "

1 "List All Paging Spaces"
2 "Add Another Paging Space"
3 "VOLUME GROUP name"
4 "Volume group name"
5 "SIZE of paging space (in logical partitions)"
6 "PHYSICAL VOLUME name"
7 "Start using this paging space NOW?"
8 "Use this paging space each time the system is\n\
\tRESTARTED?"
9 "Change / Show Characteristics of a Paging Space"
10 "PAGING SPACE name"
11 "Paging space name"
12 "Physical volume name"
13 "Remove a Paging Space"
14 "Activate a Paging Space"
15 "NUMBER of additional logical partitions"
