$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)75        1.1  src/msg/bos/base/sm_cmdalog.msg, bosmsg, msg411, GOLD410 3/7/94 15:22:28

$
$ COMPONENT_NAME:  (CMDALOG) cmdalog.50
$
$ FUNCTIONS: (none)
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$ Warning -- do not remove the "$quote ~" line below.
$            It is needed to keep gencat from failing when this
$            set is merged with other sets that use other quote characters.

$ $ alog messages
$set 50
$quote ~
1 Show an Alog File 
2 Alog TYPE 
3 Alog File NAME
4 Change / Show Characteristics of an Alog File 
5 Alog File SIZE
6 VERBOSITY
7 Alog
