$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)56	1.1  src/msg/bos/base/strclean.msg, bosmsg, msg411, GOLD410 2/9/94 09:20:19
$
$ COMPONENT_NAME: (CMDPSE) STREAMS commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ Messages for strinfo.
$ Do not translate strinfo.
$ Message numbers have been assigned a range of XXX - YYY
$
$quote "		define quote character.
$set MS_STRCLEAN	Define initial set#

USAGE1	"usage: strclean [-d logdir] [-a age]\n"
