$ ENGLISH_SOURCE_VERSION= 1.6
$ @(#)60	1.1  src/msg/bos/base/strings.msg, bosmsg, msg411, GOLD410 2/9/94 09:20:38
$
$ COMPONENT_NAME: (CMDSCAN) commands that scan files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "         define quote character.
$ messages for strings
$len
$set MS_STRINGS        Define initial set#

USAGE	"Usage: strings [-a | -] [-o] [-t format] [-n number | -number] [file ...]\n"
$ Do not translate strings.
NVAL_MAX	"0652-142 strings: string length cannot be larger than %d"
$ Do not translate strings.

