$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)59	1.1  src/msg/bos/base/strinfo.msg, bosmsg, msg411, GOLD410 2/9/94 09:20:34
$
$ COMPONENT_NAME: (CMDPSE) STREAMS commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ Messages for strinfo.
$ Do not translate strinfo.
$ Message numbers have been assigned a range of XXX - YYY
$
$quote "		define quote character.
$set MS_STRINFO		Define initial set#

$ note:
$	The "%s" in all three USAGE messages must line up
$	after translation.
 
USAGE1	"strinfo: %s -m\n"
USAGE2	"         %s -h\n"
USAGE3	"         %s -q\n"
