$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)67	1.1  src/msg/bos/base/stty-rs.msg, bosmsg, msg411, GOLD410 2/9/94 09:21:33

$
$ COMPONENT_NAME: CMDTTY terminal messuages for tty
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$
$ messages for command sysline
$

$set MS_STTY_RS

$quote "

UNKNOWN    "%s: %s unknown\n"
DMAUSAGE   "Usage %s dma level\n"
RTRIGUSAGE "Usage %s rtrig level\n"
TBCUSAGE   "Usage %s tbc level\n"
MILUSAGE   "Usage %s mil level\n"
