$ ENGLISH_SOURCE_VERSION= 1.6
$ @(#)69	1.1  src/msg/bos/base/style.msg, bosmsg, msg411, GOLD410 2/9/94 09:21:44
$
$ COMPONENT_NAME: (CMDTEXT) Text Formatting
$
$ FUNCTIONS: style.msg
$
$ ORIGINS: 26,27,28
$
$ This module contains IBM CONFIDENTIAL code. -- (IBM
$ Confidential Restricted when combined with the aggregated
$ modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$ messages for style.sh
$

$set MS_SUBNDX
$ Do not translate output formats used with C programs such as:
$ 	%d %i %x %X %u %c %s %f %e %E %g %G %p %n %ld
$ Do not translate shell variables such as:
$ 	$# $? $$ $! $- {$0 $1 $2 .... $some number}
$quote "
$ messages for style.sh


1 "Usage: %s [-r Number] [-l Number] [-e] [-p] [-n] [-N] [-a] [-P] \n\t[-mm|-ms|-me|-ma] [-li|+li] [-k] [File]\n"
2 "style: 1001-500 %s is not a valid flag.\n"
