$ ENGLISH_SOURCE_VERSION= 1.7
$ @(#)71	1.1  src/msg/bos/base/sum.msg, bosmsg, msg411, GOLD410 2/9/94 09:21:55
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1985, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 690 - 699 reserved for this file.
$
$set MS_SUM
$ Do not translate sum

OPENERR  "sum: 0653-690 Cannot open %s.\n"
READERR "sum: 0653-691 Cannot read from %s.\n"
USAGE "Usage: sum [-o|r] [FileName...]\n"
USAGE1 "Usage: sum [-i][-o|r] [FileName...]\n"
