$ ENGLISH_SOURCE_VERSION= 1.5.1.1
$ @(#)82	1.1  src/msg/bos/base/tab.msg, bosmsg, msg411, GOLD410 2/9/94 09:22:52
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1985, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 700 - 709 reserved for this file.
$
$set MS_TAB
$ Do not translate tab:


NAMLENERR       "0653-701 The specified file name is too long."
NOTAFILE        "0653-702 The specified parameter is not a file."
TABUSAGE	"Usage: tab [-e] [File...]\n"
UNTABUSAGE	"Usage: untab [File...]\n"



