$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)84	1.1  src/msg/bos/base/tabs.msg, bosmsg, msg411, GOLD410 2/9/94 09:22:59

$ COMPONENT_NAME: CMDTTY terminal control commands
$
$ FUNCTIONS: .msg file for tabs
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

$set MS_TABS

$quote "

UNKNOWN "unknown tab code"
ILLEGALINC "illegal increment"
ILLEGALTAB "illegal tabs"
FILE "file indirection"
OPEN "can't open"
