$ ENGLISH_SOURCE_VERSION= 1.8
$ @(#)98\t1.1  src/msg/bos/base/tee.msg, bosmsg, msg411, GOLD410 2/9/94 09:24:18
$
$ COMPONENT_NAME: (CMDSCAN) commands that scan files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "         define quote character.
$len
$set MS_TEE        Define initial set#

NO_FILE              "tee: 0652-044 Cannot open %s.\n"
USAGE		"Usage: tee [-ai] [file ...]\n"
$	Number 99-108 are reserve for this message file.
