$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)81 1.1 src/msg/bos/base/termdef.msg, bosmsg, msg411, GOLD410 4/8/94 09:36:36
$
$
$ COMPONENT_NAME: CMDTTY terminal control commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27, 83
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1994
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ LEVEL 1, 5 Years Bull Confidential Information
$
$set MS_TERMDEF
$
$quote "
$

USAGE "Usage: termdef [-t | -c | -l]\n"
