$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)01	1.1  src/msg/bos/base/termc.msg, bosmsg, msg411, GOLD410 2/9/94 09:24:33
$ COMPONENT_NAME: (LIBTERMC) Termcap Library
$
$ FUNCTIONS: 
$
$ ORIGINS: 27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

$set MS_TERMC
$quote "
MS_TOOLONG 1235-001 "Termcap entry too long\n"
MS_INFINITE 1235-002 "Infinite tc= loop\n"
MS_BAD 1235-003 "Bad termcap entry\n"
