$ ENGLISH_SOURCE_VERSION= 1.6
$ @(#)20    1.1  src/msg/bos/base/tty.msg, bosmsg, msg411, GOLD410 2/9/94 09:25:52
$
$ COMPONENT_NAME: (CMDSTAT) status
$
$ FUNCTIONS:
$
$ ORIGINS: 27, 71
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$
$ (c) Copyright 1990, 1991, 1992 OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$ OSF/1 1.1
$

$quote "
$set MS_TTY
$ Do not translate tty.

USAGE "Usage: tty [-s]\n"
NOTTTY "tty: 0551-011 Standard input is not a tty.\n"
