$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)39	1.1  src/msg/bos/base/ul.msg, bosmsg, msg411, GOLD410 2/9/94 09:27:00

$ COMPONENT_NAME: CMDTTY terminal control commands
$
$ FUNCTIONS: .msg file for ul
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

$set MS_UL

$quote "

USAGE "Usage: %s [ -i ] [ -tTerm ] file...\n"
TROUBLE "trouble reading termcap"
ESCAPE "Unknown escape sequence in input: %o, %o\n"

