$ ENGLISH_SOURCE_VERSION= 1.2
$ @(#)50	1.1  src/msg/bos/base/unixset.msg, bosmsg, msg411, GOLD410 2/9/94 09:27:34
$
$ COMPONENT_NAME:  (SYSPFS) syspfs.msg
$
$ FUNCTIONS: (none)
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$set 1
$quote "

$
$ set for unixset (place holder)
$
SET_NONE 1

$
$ setno for syspfs
$
SET_SYSPFS 2



