$ ENGLISH_SOURCE_VERSION= 1.1
$ @(#)53    1.1 src/msg/bos/base/users.msg, bosmsg, msg411, GOLD410 2/9/94 09:27:45
$
$ COMPONENT_NAME: (CMDSTAT) status
$
$ FUNCTIONS:
$
$ ORIGINS: 27, 18
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1991
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "

$set MS_USERS

TOO_MANY	"users: Too many users\n"
$ Do not translate 'users:'; ... "Too many users" may be translated.
