$ ENGLISH_SOURCE_VERSION= 1.5
$ @(#)70\t1.1  src/msg/bos/base/whereis.msg, bosmsg, msg411, GOLD410 2/9/94 09:28:41
$
$ COMPONENT_NAME: (CMDSCAN) commands that scan files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "         define quote character.
$ messages for whereis
$len
$set MS_WHEREIS        Define initial set#

USAGE                "Usage: whereis [-sbmu] [-SBM Directory ... -f] Name ...\n"
$ $ Verify the usage statement.
$       Do not translate whereis or the flags sbmuSBMf.
