$ ENGLISH_SOURCE_VERSION= 1.3
$ @(#)88        1.2  src/msg/bos/base/yacc_user.msg, bosmsg, msg411, GOLD410 4/7/94 12:06:43
$
$ COMPONENT_NAME: (CMDLANG) Language Utilities
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ To ensure binary compatability between releases, do not change the
$ order or numbering of the following messages.
1               "Syntax Error - Cannot Backup"
2               "YACC Stack Overflow"
3               "Syntax Error"
