$ @(#)58	1.1  src/tenplus/util/addrem.msg, tenplus, tenplus411, GOLD410 3/17/93 14:04:27
$
$ COMPONENT_NAME: (INED) INed Editor
$ 
$ ORIGINS:  27
$ 
$ This module contains IBM CONFIDENTIAL code. -- (IBM
$ Confidential Restricted when combined with the aggregated
$ modules for this product)                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$quote "
$
$set MS_ADDREM 
$
$ Translator:  do not translate anthing that looks like %s or %d or
$ %1$s or %2$d etc.
$ Do not translate "addrem".
$
M_USAGE "Usage: addrem String"
$ Do not translate addrem
$
M_OPEN "%1$s: 0611-227 Cannot find or open file %2$s."
$
M_HOME "0611-228 Cannot evaluate the $HOME variable.\n\
Set the shell variable HOME and export it."
$ Do not translate $HOME, HOME
$
M_MALLOC "0611-229 Cannot allocate memory in the makename routine."
$ Do not translate "makename".
$
M_LOCK "0611-230 Cannot open lock file %s."
$ Do not translate lock
$
M_UNLOCK "0611-231 Cannot delete file %s."
