# @(#)44	1.7  src/msg/Makefile, bosmsg, msg411, 9439C411a 9/30/94 08:31:59
#
# COMPONENT_NAME: bosmsg
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS = 

.if defined(BUILD_PII)
SUBDIRS	=	bos    
.endif

.include <${RULES_MK}>
