# @(#)61        1.3  src/bos/usr/sbin/mkboot/Makefile, bosboot, bos411, 9428A410j 5/16/94 16:10:45
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= mkboot
CATFILES	= mkboot.cat

ILIST		= mkboot
IDIR		= /usr/sbin/

LIBS		= -lodm -lcfg

.include <${RULES_MK}>
