# @(#)10    1.1  src/rspc/usr/ccs/Makefile, Makefiles, rspc41J, 9510A  3/8/95  07:36:56
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= lib

EXPLIB_SUBDIRS		= lib

SUBDIRS			= lib

.include <${RULES_MK}>

