# @(#)10	1.2  src/bos/usr/sbin/backbyname/Makefile, cmdarch, bos411, 9428A410j 4/6/93 08:36:43
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= backbyname
MSGHDRS		= bbyname_msg.h
CATFILES	= bbyname.cat
HFILES		= ${MSGHDRS}

ILIST		= backbyname
IDIR		= /usr/sbin/

.include <${RULES_MK}>
