# @(#)20        1.2  src/bos/usr/sbin/install/inurdsd/Makefile, cmdinstl, bos411, 9428A410j 11/6/92 12:40:44
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= inurdsd
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= inurdsd
IDIR		= /usr/sbin/

INCFLAGS	= -I../messages -I../include

LIBS		= -linulib -ls -lPW -lcfg -lIN

.include <${RULES_MK}>
