# @(#)24        1.2  src/bos/usr/sbin/install/inutoc/Makefile, cmdinstl, bos411, 9428A410j 11/7/92 15:31:07
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= inutoc
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= inutoc
IDIR		= /usr/sbin/

INCFLAGS	=-I../messages -I../include

LIBS		= -linulib -ls -lcfg -lswvpd -lodm -lPW

.include <${RULES_MK}>
