# @(#)84        1.1  src/bos/usr/sbin/bindprocessor/Makefile, cmdmp, bos411, 9428A410j 12/15/93 07:35:17

# COMPONENT_NAME: (CMDMP)
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# LEVEL 1,5 Years Bull Confidential Information
#

PROGRAMS	= bindprocessor
MSGHDRS		= bindprocessor_msg.h
CATFILES	= bindprocessor.cat
HFILES		= ${MSGHDRS}

ILIST		= bindprocessor
IDIR		= /usr/sbin/

.include <${RULES_MK}>
