# @(#)43        1.3  src/bos/usr/sbin/skulker/Makefile, cmdcntl, bos411, 9428A410j 3/15/94 17:33:47
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


MSGHDRS		= skulker_msg.h
CATFILES	= skulker.cat
OTHERS		= skulker.cat

SCRIPTS		= skulker

ILIST		= skulker
IDIR		= /usr/sbin/

NOUPDATE_LIST	= /usr/sbin/skulker

.include <${RULES_MK}>
