$ @(#)60        1.8  src/bos/usr/sbin/devnm/devnm.msg, cmdfiles, bos411, 9428A410j 8/3/93 17:23:21
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 145 - 154 reserved for this file.
$
$               GLOBAL COMMENT FOR TRANSLATORS
$ Do not translate devnm -- this is the command name.
$ Do not translate /dev.
$set MS_DEVNM
$
CANTOPEN "devnm: 0653-145 Cannot open the directory /dev.\n"
$
STATERR "devnm: 0653-146 Cannot get status on file %s in directory /dev.\n"
$
NOTLOCAL "devnm: 0653-147 %s is not in a local file system.\n"
