# @(#)37        1.2  src/bos/usr/sbin/devnm/Makefile, cmdfiles, bos411, 9428A410j 1/22/93 15:41:06
# COMPONENT_NAME: cmdfiles
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= devnm
MSGHDRS		= devnm_msg.h
CATFILES	= devnm.cat
HFILES		= ${MSGHDRS}

ILIST		= devnm
IDIR		= /usr/sbin/


.include <${RULES_MK}>
