# @(#)88        1.2  src/bos/usr/ucb/sendbug/Makefile, cmdmailx, bos411, 9428A410j 1/21/93 18:05:56
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= sendbug
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= sendbug
IDIR		= /usr/bin/


.include <${RULES_MK}>
