# @(#)06	1.1  src/rspc/usr/lib/boot/softros/lib/libc/Makefile, rspc_softros, rspc411, GOLD410 4/18/94 15:47:26
#
#   COMPONENT_NAME: RSPC_SOFTROS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libsrlibc.a
EXPLIB_TARGETS	= export_libsrlibc.a

IDIR		= /usr/lib/masters/

OFILES		= ctype.o stdio.o stdlib.o string.o

INCFLAGS	= -I${MAKETOP}/rspc/usr/lib/boot/softros/include

CFLAGS		= -qcpluscmt -qarch=ppc

.include <${RULES_MK}>
