# @(#)61	1.1  src/rspc/kernext/isa/itok/isatok.trc.S, isatok, rspc411, GOLD410 5/2/94 16:01:23
#
#   COMPONENT_NAME: ISATOK
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt
+334 1.0 "@tokdd" \
        "TOK DD XMT: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4 

+335 1.0 "@tokdd" \
        "TOK DD RCV: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+336 1.0 "@tokdd" \
        "TOK DD GEN: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+337 1.0 "@tokdd" \
        "TOK DD ERR: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4
