#
# COMPONENT_NAME: CDRMSAMP
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



ILIST		= cdromt.c cdromb.c cdromdd.h
IDIR		= /usr/samples/cdrom/

.include <${RULES_MK}>
