# @(#)81        1.1  src/bos/usr/sbin/cpu_state/Makefile, cmdmp, bos411, 9428A410j 12/15/93 07:34:54

# COMPONENT_NAME: (CMDMP)
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# LEVEL 1,5 Years Bull Confidential Information
#

PROGRAMS	= cpu_state
MSGHDRS		= cpu_state_msg.h
CATFILES	= cpu_state.cat
HFILES		= ${MSGHDRS}

ILIST		= cpu_state
IDIR		= /usr/sbin/

LIBS            = -lodm -lcfg

.include <${RULES_MK}>
