# @(#)66	1.7  src/tenplus/lib/short/Makefile, tenplus, tenplus411, GOLD410 6/8/93 13:45:14
#
# COMPONENT_NAME: (INED) INed Editor
# 
# ORIGINS:  9, 10, 27
# 
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
# 
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.


LIBRARIES = libshort.a
INCFLAGS = -I${MAKETOP}/tenplus/include
OFILES = i_addtype.o i_read.o	i_strcpy.o i_strncpy.o i_cat.o        \
	i_realloc.o i_string.o	i_delete.o i_pad.o i_seq.o i_strlen.o     \
	i_write.o	i_insert.o i_print.o i_smear.o i_strncmp.o

.include <${RULES_MK}>
