# @(#)03        1.3  src/rspc/usr/lib/methods/cfgsio_isa/Makefile, rspccfg, rspc41J, 9513A_all 3/28/95 16:10:49
# COMPONENT_NAME: rspccfg
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994,1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


PROGRAMS	= cfgsio_isa

OFILES		= cfgsio_isa.o

INCFLAGS        +=

ILIST		= cfgsio_isa
IDIR		= /usr/lib/methods/


LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
