# static char sccsid[] = "@(#)37	1.3  src/rspc/usr/lbin/Makefile, isatty, rspc41J, 9513A_all 3/24/95 15:14:09";
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS			= tty ientdd itok_dd stok_dd

.include <${RULES_MK}>
