# @(#)50       1.3  src/bos/usr/samples/kernel/Makefile, kersamp, bos411, 9434A411a 8/21/94 20:56:27 
# COMPONENT_NAME: KERSAMP
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS                = vmtune schedtune
ILIST                   = schedtune.c vmtune.c schedtune vmtune
IDIR                    = /usr/samples/kernel/

INCFLAGS                =-I../../../kernel/vmm/POWER

.include <${RULES_MK}>
