# @(#)33        1.3  src/bos/usr/sbin/sar/Makefile, cmdstat, bos411, 9428A410j 7/26/93 11:32:28
# COMPONENT_NAME:  (CMDSTAT)
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= sar
MSGHDRS		= sar_msg.h
CATFILES	= sar.cat
HFILES		= ${MSGHDRS}

INCFLAGS	= -I${MAKETOP}/bos/usr/sbin/sa/
ILIST		= sar
IDIR		= /usr/sbin/


.include <${RULES_MK}>
