# @(#)71	1.2  src/tcpip/usr/ccs/lib/libbsdutil/Makefile, tcpip, tcpip411, 9433B411a 8/17/94 09:37:52
#
# COMPONENT_NAME: tcpip
#
# FUNCTIONS:
#
# ORIGINS: 26, 27, 71
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES		= libbsdutil.a

EXPLIB_TARGETS		= export_libbsdutil.a

ILIST			= libbsdutil.a
IDIR			= /usr/ccs/lib/
IMODE			= 644

OFILES			= login.o logout.o logwtmp.o login_tty.o pty.o daemon.o

.include <${RULES_MK}>
