$ @(#)56	1.1  src/tenplus/sf_progs/fixascii.msg, tenplus, tenplus411, GOLD410 3/17/93 14:04:10
$
$ COMPONENT_NAME: (INED) INed Editor
$ 
$ ORIGINS:  27
$ 
$ This module contains IBM CONFIDENTIAL code. -- (IBM
$ Confidential Restricted when combined with the aggregated
$ modules for this product)                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$quote "
$
$set MS_FIXASCII
$
$ Translator:  do not translate anthing that looks like %s or %d or
$ %1$s or %2$d etc.
$ Do not translate the word "fixascii".
$
M_USAGE "Usage: fixascii [-ns] ASCIIFile DeltaFile"
$
M_FIXING "Fixing delta file %s."
$
M_SAVING "Saving ASCII file %s."
$
M_OPEN_NEW "fixascii: 0611-152 Cannot open delta file %s."
$
M_OPEN_TMP "fixascii: 0611-153 Cannot open temporary delta file %s."
$
M_IO_WRITE "fixascii: 0611-154 Cannot write to temporary file %s.\n\
\tThe disk may be full."
$
M_WRITE "fixascii: 0611-155 Cannot write. The disk may be full."
$
M_SF_CLOSE "fixascii: 0611-156 Cannot run sf_close. The disk may be full."
$
M_FCLOSE "fixascii: 0611-157 Cannot close the input file."
$
M_OPEN_ASCII "fixascii: 0611-158 Cannot open the ASCII file %s."
$
M_M_STAT "fixascii: 0611-159 Cannot get status on file %s."
$
M_E_STAT "fixascii: 0611-160 Cannot get status on file %s."
$
M_E_READ "fixascii: 0611-161 Cannot read file %s."
$
M_E_CREATE "fixascii: 0611-162 Cannot create file %s."
$
M_READ_IDX "0611-163 There is a read error: index %1$d, file %2$s."
$ Do not translate "read error, index %1$d, file %2$s".
$
M_DISK_FL "0611-164 Cannot write to text file %s. The disk may be full."
$
M_REOPEN "fixascii: 0611-165 Cannot reopen file %s."
$
M_RESTAT "fixascii: 0611-166 Cannot get status on file %s again."
$
M_SEEK "fixascii: 0611-167 Cannot seek to location %D."
$ Do not translate seek, %D
