$ @(#)55	1.1  src/tenplus/sf_progs/newfile.msg, tenplus, tenplus411, GOLD410 3/17/93 14:04:03
$
$ COMPONENT_NAME: (INED) INed Editor
$ 
$ ORIGINS:  27
$ 
$ This module contains IBM CONFIDENTIAL code. -- (IBM
$ Confidential Restricted when combined with the aggregated
$ modules for this product)                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$quote "
$
$set MS_NEWFILE 
$
$ Translator:  do not translate anthing that looks like %s or %d or
$ %1$s or %2$d etc.
$ Do not translate the word "newfile".
$
M_USAGE "Usage: Newfile TextFile [DeltaFile]"
$
M_OPEN "newfile: 0611-177 Cannot open text file %s."
$
M_CREATE "newfile: 0611-178 Cannot create delta file %s."
$
M_WRITE "newfile: 0611-179 Cannot write record %d. The disk may be full."
$
M_CLOSE "newfile: 0611-180 Cannot close. The disk may be full."
