# @(#)10  1.2  src/rspc/kernext/disp/pcifga/inc/Makefile, pcifga, rspc411, GOLD410 5/24/94 16:31:33
#
#   COMPONENT_NAME: pcifga
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPDIR          = /kernel/include/graphics/

INCLUDES        = fgadds.h fga_reg.h fga_regval.h \
		fga.h fgaddf.h fgaldat.h 

.include <${RULES_MK}>


