# @(#)97	1.2  src/tcpip/Makefile, tcpip, tcpip411, GOLD410 12/8/92 12:58:33
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 10  26  27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
# (c) Copyright 1990, 1991, 1992 OPEN SOFTWARE FOUNDATION, INC. 
# ALL RIGHTS RESERVED 
#
#

SUBDIRS			= usr etc

SETUP_SUBDIRS		= usr

EXPINC_SUBDIRS		= usr
#EXPLIBC_SUBDIRS	= usr
#EXPLOADER_SUBDIRS	= sbin
#EXPSHLIB_SUBDIRS	= usr
EXPLIB_SUBDIRS		= usr

.include <${RULES_MK}>
