# @(#)67        1.1  src/bos/usr/sys/inst.data/Makefile, pkg, bos411, 9428A410j 12/3/93 16:45:56
# COMPONENT_NAME: pkg
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS			= sys_bundles

.include <${RULES_MK}>
