# @(#)72        1.1  src/bos/usr/sbin/no/Makefile, cmdnet, bos411, 9428A410j 8/5/92 17:44:12
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= no
MSGHDRS		= no_msg.h
CATFILES	= no.cat
HFILES		= ${MSGHDRS}

ILIST		= no
IDIR		= /usr/sbin/


.include <${RULES_MK}>
