# @(#)15        1.2  src/bos/usr/sbin/machstat/Makefile, cmdoper, bos411, 9428A410j 3/3/93 16:34:20
#
# COMPONENT_NAME: CMDOPER
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993.
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= machstat

ILIST		= machstat
IDIR		= /usr/sbin/

.include <${RULES_MK}>
