# @(#)05	1.9  src/tcpip/usr/sbin/Makefile, tcpip, tcpip411, GOLD410 3/30/94 17:16:07
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 10  26  27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH			= ${TARGET_MACHINE}
SUBDIRS                 = chnamsv chprtsv chrctcp gated hostent htable inetd \
			iptrace ipreport ip_auditpr chservices chsubserver\
			lsadpnm lsnamsv lsprtsv mkhosts mknamsv mkprtsv \
			mktcpip named namerslv rmnamsv rmprtsv routed \
			rwhod timed snmpd snmpinfo tcpdump mosy oiddump \
			compat

.include <${RULES_MK}>
