# @(#)74        1.6  src/rspc/kernext/Makefile, Makefiles, rspc41J, 9510A 2/16/95 11:48:40
#
#   COMPONENT_NAME: Makefiles
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= inc disp

SUBDIRS		= disp isa pci pcmcia tty rspcios pm idecdrom idedisk

.include <${RULES_MK}>
