$ @(#)48	1.2  src/bos/usr/sbin/strace/strace.msg, cmdpse, bos411, 9428A410j 6/11/91 11:31:23
$
$ COMPONENT_NAME: (CMDPSE) STREAMS commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ Messages for strace.
$ Do not translate strace.
$ Message numbers have been assigned a range of XXX - YYY
$
$quote "		define quote character.
$set MS_STRACE		Define initial set#

MSG1	"strace: cannot open log device"
USAGE1	"usage: strace [mid sid level] ...\n"
MSG2	"strace: already registered\n"
