# @(#)25        1.2  src/bos/usr/sbin/snap/Makefile, cmdsnap, bos411, 9432A411a 8/4/94 13:29:42
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= check_unix
SCRIPTS		= snap
MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}

ILIST		= snap check_unix
IDIR		= /usr/sbin/
check_unix_IDIR  = /usr/lib/ras/

OFILES		= check_unix.o read_dump.o


.include <${RULES_MK}>
