# @(#)38        1.1  src/bos/usr/sbin/slibclean/Makefile, Makefiles, bos411, 9428A410j 9/4/92 13:13:51
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= slibclean
MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}

ILIST		= slibclean
IDIR		= /usr/sbin/


.include <${RULES_MK}>
