# @(#)09        1.1  src/bos/usr/sbin/install/inu_tape_dd/Makefile, cmdinstl, bos411, 9428A410j 3/23/94 14:40:42
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= inu_tape_dd
MSGHDRS		= 
CATFILES	= 
HFILES		= 

ILIST		= inu_tape_dd
IDIR		= /usr/lib/instl/

INCFLAGS	= 

CC_OPT_LEVEL	=

OFILES		= inu_tape_dd.o 

LIBS		= -linulib 

.include <${RULES_MK}>
