# @(#)44        1.1  src/bos/usr/sbin/syncd/Makefile, cmdfs, bos411, 9428A410j 8/31/92 19:22:23
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= syncd
MSGHDRS		= syncd_msg.h
CATFILES	= syncd.cat
HFILES		= ${MSGHDRS}

ILIST		= syncd
IDIR		= /usr/sbin/


.include <${RULES_MK}>
