# @(#)96	1.8  src/tenplus/lib/window/Makefile, tenplus, tenplus411, GOLD410 10/27/93 11:40:03
#
# COMPONENT_NAME: (TENPLUS) INed Editor
#
# FUNCTIONS:
#
# ORIGINS:  9, 10, 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES = libwin.a 
INCFLAGS = -I${MAKETOP}/tenplus/include
OFILES = _wnprint.o	wn_free.o	wn_init.o	wn_print.o wn_read.o wn_write.o
CFLAGS = -DVBLSCR

.include <${RULES_MK}>

