# @(#)39        1.2  src/bos/usr/sbin/restbyname/Makefile, cmdarch, bos411, 9428A410j 7/2/93 14:24:12
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= restbyname
MSGHDRS		= rbyname_msg.h
CATFILES	= rbyname.cat
HFILES		= ${MSGHDRS}

ILIST		= restbyname
IDIR		= /usr/sbin/

INCFLAGS	= -I../backbyname

OFILES		= restbyname.o restorx.o

.include <${RULES_MK}>
