# @(#)61        1.1  src/bos/usr/sbin/audit/Makefile, cmdsaud, bos411, 9428A410j 8/5/92 17:36:40
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= audit
MSGHDRS		= audit_msg.h
CATFILES	= audit.cat
HFILES		= ${MSGHDRS}

ILIST		= audit
IDIR		= /usr/sbin/

OFILES		= audit.o audutil.o cfgcutil.o

LIBS 		= -ls

.include <${RULES_MK}>
