# @(#)36	1.1  src/bos/usr/sbin/tapechk/Makefile, cmdarch, bos411, 9428A410j 12/2/92 15:54:53
# COMPONENT_NAME:  CMDARCH
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= tapechk

ILIST		= tapechk
IDIR		= /usr/sbin/


.include <${RULES_MK}>

