# @(#)61        1.4  src/rspc/usr/lib/boot/Makefile, bosboot, rspc41J, 9517B_all 4/9/95 23:08:42
#
# COMPONENT_NAME: rspccfg
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS	= softros

SUBDIRS		= softros protoext disable_hibernation

SCRIPTS		= rspc.cd.proto rspc.disk.proto

ILIST		= rspc.cd.proto rspc.disk.proto

IDIR		= /usr/lib/boot/

INCFLAGS	=-I${MAKETOP}/bos/kernel

.include <${RULES_MK}>
