$ @(#)29        1.5.1.2  src/bos/usr/sbin/catman/catman.msg, cmdman, bos411, 9428A410j 10/19/93 17:19:06
$
$ COMPONENT_NAME: (CMDMAN) commands that allow users to read online
$                          documentation
$
$ FUNCTIONS: none
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "         define quote character.
$ messages for catman
$len
$set MS_CATMAN        Define initial set#
$ Do not translate catman.
USAGE	"Usage: catman [-n | -p | -w] [-M Path] [Sections]\n"
NOTDIR	"catman: 0703-101 %s is not a directory.\n"
BADMAN 	"catman: nroff: 0703-102 %1$s: The error number is %2$d.\n"
$ Do not translate nroff.
STATUS	"catman: 0703-102 %s: The error number is %d.\n"
M_MSG_1	"catman: 0703-103 Cannot open the database %s.\n"
M_MSG_2	"catman: 0703-104 The ispaths file is in the wrong format.\n"
$ Do not translate ispaths.
M_MSG_3	"catman: 0703-105 Cannot access InfoExplorer Databases.\n"
$ Do not translate InfoExplorer.
NODB	"catman: 0703-106 Cannot open %s.\n"
