# @(#)76        1.4  src/rspc/kernext/pci/Makefile, Makefiles, rspc41J, 9513A_all 3/21/95 11:39:24
#
#   COMPONENT_NAME: MAKEFILES
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS         = ncr810 pcivca kent stok

.include <${RULES_MK}>
