$ @(#)67        1.5.1.2  src/bos/usr/sbin/mvdir/mvdir.msg, cmdfiles, bos411, 9428A410j 9/1/93 16:48:54
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files      
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 380 - 384 reserved for this file.
$
$set MS_MVDIR

USAGE "Usage: mvdir Directory1 Directory2\n"
$ Do not translate mvdir.
