# @(#)84        1.2  src/bos/usr/sbin/chdev/Makefile, Makefiles, bos411, 9428A410j 9/13/92 14:37:11
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../mkdev

PROGRAMS	= chdev
MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}

ILIST		= chdev
IDIR		= /usr/sbin/

OFILES		= chdev.o cfglib.o defaultmsg.o

LIBS		= -ls -lodm -lcfg

.include <${RULES_MK}>
