# @(#)80        1.28  src/rspc/usr/lib/methods/Makefile, Makefiles, rspc41J, 9513A_all 3/28/95 11:50:38
#
#   COMPONENT_NAME: MAKEFILES
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993, 1994, 1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= cfg_fga cfg_hga cfgc1x cfgisatok cfg_bbl \
		  cfgisaent define_rspc chgisaent chgisatok \
		  cfgbus_pci cfgkm_isa cfgppa_isa cfgasync_rspc \
		  cfgmouse_isa cfgsio_isa chggen_rspc cfgbus_isa \
		  cfgfda_isa cfgkbd_isa cfgncr_scsi cfgsys_rspc \
		  cfgbus_pcmcia cfgpctok cfgpcent \
		  cfg_wfg cfgpcivca startpm cfgpmc ucfgpmc \
		  probe_ibmtok probe_ibment cfg_gga cfg_iga \
		  cfgpcasync ucfgpcasync cfgkent cfgdgric_isa \
		  cfgataide cfgidedisk cfgidecdrom cfgstok \
		  cfgpm8301 ucfgpm8301
		   

.include <${RULES_MK}>
