# @(#)64        1.10  src/bos/usr/samples/Makefile, bossamp, bos411, 9428A410j 6/28/94 13:39:01

#
# COMPONENT_NAME: BOSSAMP
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= cdrom cfg fp fd kernel ndd dlpi

SCRIPTS         = README
ILIST           = README
IDIR            = /usr/samples/

.include <${RULES_MK}>
