# @(#)61	1.1  src/rspc/etc/acfgd/Makefile, Makefiles, rspc41J, 9509A_all 2/20/95 10:49:16
#
#   COMPONENT_NAME: Makefiles
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= action_after_mkdev_tok action_before_rmdev_tok \
                  action_after_mkdev_ent action_before_rmdev_ent

ILIST		= ${SCRIPTS}
IDIR		= /etc/acfgd/


.include <${RULES_MK}>

