# @(#)41        1.2  src/bos/usr/sbin/restore/Makefile, cmdarch, bos411, 9428A410j 4/6/93 08:11:35
# COMPONENT_NAME: (CMDARCH) archive files
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= restore
MSGHDRS		= restore_msg.h
CATFILES	= restore.cat
HFILES		= ${MSGHDRS}

ILIST		= restore
IDIR		= /usr/sbin/

INCFLAGS        = -I../backbyname

.include <${RULES_MK}>
