# @(#)64	1.2  src/rspc/usr/sbin/Makefile, Makefiles, rspc41J, 9509A_all 1/26/95 12:35:06
#
#   COMPONENT_NAME: Makefiles
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994, 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= pcmciastat acfgd

.include <${RULES_MK}>
