# @(#)55        1.1  src/bos/usr/samples/dlpi/makefile, sysxpse, bos411, 9428A410j 6/28/94 12:44:54
#
#   COMPONENT_NAME: SYSXPSE
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES		= Makefile sdlpi.c cdlpi.c

ILIST			= ${DATAFILES}
IDIR			= /usr/samples/dlpi/

.include <${RULES_MK}>
