$ @(#)57        1.2  src/bos/usr/sbin/dtappintegrate/dtappintegrate.msg, dtappintegrate, bos411, 9428A410j 4/7/94 12:20:27
$
$   COMPONENT_NAME: dtappintegrate
$
$   FUNCTIONS: none
$
$   ORIGINS: 27
$
$
$   (C) COPYRIGHT International Business Machines Corp. 1993
$   All Rights Reserved
$   Licensed Materials - Property of IBM
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ **   Description:
$ **   ------------
$ **   This is the source message catalog file for dtappintegrate.

$set 1
$   COMMENT TO TRANSLATORS:  Do not translate any of the <<<< or >>>>
1 <<<<<<< START OF APPLICATION INTEGRATION >>>>>>>\n
$   COMMENT TO TRANSLATORS:  Do not translate any of the <<<< or >>>>
2 <<<<<<< END  OF  APPLICATION INTEGRATION >>>>>>>\n
$   COMMENT TO TRANSLATORS:  Do not translate $SCRIPT_NAME, -s, -t, -l, -u
$   COMMENT TO TRANSLATORS:  Do not translate; this msg is no longer used
3 Usage: $SCRIPT_NAME -s <app_root> [-t <target>] [-l <language>] [-u]\n
$   COMMENT TO TRANSLATORS:  Do not translate $0
$   COMMENT TO TRANSLATORS:  Do not translate; this msg is no longer used
4 Error: Must be root user to run $0!\n
$   COMMENT TO TRANSLATORS:  Do not translate $dir
$   COMMENT TO TRANSLATORS:  Do not translate; this msg is no longer used
5 Error: Could not create $dir  directory!\n
$   COMMENT TO TRANSLATORS:  Do not translate -s
6 Error: Did not specify -s option!\n
$   COMMENT TO TRANSLATORS:  Do not translate $APP_PATH
$   COMMENT TO TRANSLATORS:  Do not translate; this msg is no longer used
7 Error: $APP_PATH is not a directory!\n
$   COMMENT TO TRANSLATORS:  Do not translate $APP_PATH
$   COMMENT TO TRANSLATORS:  Do not translate; this msg is no longer used
8 Error: Can not read $APP_PATH directory!\n
$   COMMENT TO TRANSLATORS:  Do not translate $LOGFILE
$   COMMENT TO TRANSLATORS:  Do not translate; this msg is no longer used
9 See $LOGFILE file for more information\n
10 Unintegration Complete\n
11 No files to unintegrate\n
12 Integration Complete\n
13 No files to integrate\n
$
$   COMMENT TO TRANSLATORS:  Do not translate %s, -s, -t, -l, -u
$   COMMENT TO TRANSLATORS:  This is new msg that will replace msg #3
23 Usage: %s -s <app_root> [-t <target>] [-l <language>] [-u]\n
$   COMMENT TO TRANSLATORS:  Do not translate %s
$   COMMENT TO TRANSLATORS:  This is new msg that will replace msg #4
24 Error: Must be root user to run %s!\n
$   COMMENT TO TRANSLATORS:  Do not translate %s
$   COMMENT TO TRANSLATORS:  This is new msg that will replace msg #5
25 Error: Could not create  %s  directory!\n
$   COMMENT TO TRANSLATORS:  Do not translate %s
$   COMMENT TO TRANSLATORS:  This is new msg that will replace msg #7
27 Error: %s  is not a directory!\n
$   COMMENT TO TRANSLATORS:  Do not translate %s
$   COMMENT TO TRANSLATORS:  This is new msg that will replace msg #8
28 Error: Can not read  %s  directory!\n
$   COMMENT TO TRANSLATORS:  Do not translate %s
$   COMMENT TO TRANSLATORS:  This is new msg that will replace msg #9
29 See %s file for more information\n
