# @(#)58	1.1  src/bos/usr/sbin/dtappintegrate/Makefile, dtappintegrate, bos411, 9428A410j 12/6/93 16:40:15
#
#   COMPONENT_NAME: dtappintegrate
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
#

SCRIPTS                  = dtappintegrate

CATFILES                 = dtappintegrate.cat

ILIST                    = ${SCRIPTS} 

IDIR                     = /usr/sbin/
IMODE                    = 500
dtappintegrate_ILINKS    = /etc/

.include <${RULES_MK}>

