# @(#)46	1.2  src/tcpip/usr/samples/snmpd/smux/sampled/makefile, snmp, tcpip411, GOLD410 9/15/93 15:34:48
#
# COMPONENT_NAME: (SNMP) Simple Network Management Protocol Daemon
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991, 1993
# All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Licensed Material - Property of IBM
#
#

.include <${MAKETOP}tcpip/usr/Make.cfg>

VPATH			= ${TARGET_MACHINE}
DATAFILES		= Makefile README sampled.c sqeping.c stats.c \
			  sampled.my sqeping.h stats.h

ILIST			= ${DATAFILES}
IDIR			= /usr/samples/snmpd/smux/sampled/
IMODE			= 644

.include <${RULES_MK}>
