# @(#)73        1.4  src/rspc/Makefile, Makefiles, rspc41J, 9509A_all 1/26/95 12:34:45
#
#   COMPONENT_NAME: MAKEFILES
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993, 1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= kernext usr

EXPLIB_SUBDIRS	= usr

SUBDIRS		= kernext usr objclass etc

.include <${RULES_MK}>
