# @(#)59	1.6  src/tenplus/e2/Makefile, tenplus, tenplus411, GOLD410 3/24/93 09:23:40

# Makefile tenplus/e2/Makefile
# COMPONENT_NAME: (INED) INed Editor
# 
# ORIGINS:  9, 10, 27
# 
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1988
# All Rights Reserved
# 
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.


SUBDIRS = \
	common

.include <${RULES_MK}>
