# @(#)65	1.17  src/tenplus/Makefile, tenplus, tenplus411, GOLD410 6/8/93 13:23:18
#
# Modified for V3.X 89.06.01

# COMPONENT_NAME: (INED) INed Editor
# 
# ORIGINS:  9, 10, 27
# 
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
# 
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

SUBDIRS =      \
	interface    \
	lib          \
	sf_progs     \
	tools        \
	keys         \
	hlib         \
	e2           \
	helpers      \
	util         \
	termcap      \
	filters      \
	include

.include <${RULES_MK}>
