# @(#)49        1.5  src/bos/usr/sbin/mpcfg/Makefile, dsaubump, bos411, 9428A410j 5/19/94 07:53:01

# COMPONENT_NAME: DSAUBUMP
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# LEVEL 1,5 Years Bull Confidential Information
#

PROGRAMS	= mpcfg
MSGHDRS		= mpcfg_msg.h
CATFILES	= mpcfg.cat
HFILES		= ${MSGHDRS} modem.h
OFILES		= mpcfg.o trans_modem.o modem_gr.o

ILIST		= mpcfg
IDIR		= /usr/sbin/

.include <${RULES_MK}>
