# @(#)14	1.1  src/tcpip/usr/samples/snmpd/dpi/dpid/makefile, snmp, tcpip411, GOLD410 9/13/93 15:05:19
#
# COMPONENT_NAME: (SNMP) Simple Network Management Protocol Daemon
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991, 1993
# All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Licensed Material - Property of IBM
#
.include <${MAKETOP}tcpip/usr/Make.cfg>

VPATH			= ${TARGET_MACHINE}
DATAFILES		= Makefile dpid.c get_dpi_port.c register.c \
			  README dpid.my mkDPI.c snmp_dpi.h

ILIST			= ${DATAFILES}
IDIR			= /usr/samples/snmpd/dpi/dpid/
IMODE			= 644

.include <${RULES_MK}>
