# @(#)43        1.2  src/bos/usr/sbin/swapon/Makefile, cmdps, bos411, 9428A410j 5/5/94 18:10:24
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../lsps

PROGRAMS	= swapon
MSGHDRS		= cmdps_msg.h
CATFILES	= cmdps.cat
HFILES		= ${MSGHDRS}

ILIST		= swapon
IDIR		= /usr/sbin/

LIBS		= -llvm -lcfg
INCFLAGS	= -I../lsps

.include <${RULES_MK}>
