# @(#)42        1.1  src/bos/usr/sbin/rmdev/Makefile, cfgmethods, bos411, 9428A410j 8/31/92 19:21:37
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../mkdev

PROGRAMS	= rmdev
MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}

ILIST		= rmdev
IDIR		= /usr/sbin/

OFILES		= rmdev.o cfglib.o defaultmsg.o

LIBS		= -ls -lodm -lcfg

.include <${RULES_MK}>
