# @(#)27	1.1  src/tcpip/usr/sbin/mkhosts/Makefile, tcpip, tcpip411, GOLD410 12/8/92 11:44:08
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 10  26  27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS                = mkhosts
MSGHDRS                 = mkhosts_msg.h
CATFILES                = mkhosts.cat

IDIR                    = /usr/sbin/
ILIST                   = mkhosts

CCTYPE                  = writable_strings
HFILES                  = ${MSGHDRS}

.include <${RULES_MK}>
