$ @(#)79	1.3  src/bos/usr/sbin/auditstream/auditstm.msg, cmdsaud, bos411, 9428A410j 3/28/91 15:13:59
$
$ COMPONENT_NAME: (CMDSAUD) security: auditing subsystem
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989-1991
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$                                                                  

$
$
$ messages for auditstream
$

$set MS_AUDITSTM

$quote "

USAGE		"Usage: auditstream [-c class[,class]*]"
ERRPRIV		"** SET_PROC_AUDIT privilege required"
ERRSUSPEND      "** cannot suspend auditing"
