# @(#)79        1.1  src/rspc/usr/lib/Makefile, Makefiles, rspc411, GOLD410 5/1/94 13:46:38
#
#   COMPONENT_NAME: MAKEFILES
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS	= boot

SUBDIRS         = boot methods

.include <${RULES_MK}>
