# @(#)86  1.3  src/bos/usr/sbin/nddstat/Makefile, nddstat, bos411, 9428A410j 3/7/94 10:54:47 
#
#   COMPONENT_NAME: NDDSTAT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= common entstat tokstat fddistat

.include <${RULES_MK}>
