# @(#)49        1.2  src/bos/usr/sbin/penable/Makefile, cmdoper, bos411, 9428A410j 3/3/93 16:36:07
#
# COMPONENT_NAME: CMDOPER
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993.
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= penable
MSGHDRS		= penable_msg.h
CATFILES	= penable.cat
HFILES		= ${MSGHDRS}

ILIST		= penable
IDIR		= /usr/sbin/

LIBS		= -lodm -lcfg

.include <${RULES_MK}>
