#  @(#)69       1.2.1.1  src/rspc/kernext/isa/ient/isaeth.trc.S, isaent, rspc41B, 412_41B_sync 1/6/95 15:46:50 
#
#   COMPONENT_NAME: ISAENT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt
+330 1.0 "@ientdd" \
	"ISAENT DD XMIT: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+331 1.0 "@ientdd" \
	"ISAENT DD RECV: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+332 1.0 "@ientdd" \
	"ISAENT DD OTHER: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+333 1.0 "@ientdd" \
	"ISAENT DD ERR: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

