/* @(#)60	1.3  src/tcpip/usr/lib/libisode/DSE-types.h, isodelib7, tcpip411, GOLD410 4/5/93 13:33:15 */
/*
 * COMPONENT_NAME: (ISODELIB7) ISODE Libraries, Release 7
 *
 * FUNCTIONS: free_DSE_PSAPaddr
 *
 * ORIGINS: 60
 *
 * FILE:	src/tcpip/usr/lib/libisode/DSE-types.h
 */

/* automatically generated by pepsy 6.0 #108 (oilers.netmgmt.austin.ibm.com), do not edit! */

#ifndef	_module_DSE_defined_
#define	_module_DSE_defined_

#ifndef	PEPSY_VERSION
#define	PEPSY_VERSION		2
#endif

#include <isode/psap.h>
#include <isode/pepsy.h>
#include <isode/pepsy/UNIV-types.h>

#include <isode/pepsy/DSE_defs.h>

struct type_DSE_PSAPaddr {
    struct qbuf *pSelector;

    struct qbuf *sSelector;

    struct qbuf *tSelector;

    struct member_DSE_0 {
        struct qbuf *member_DSE_1;

        struct member_DSE_0 *next;
    } *nAddress;
};
#define	free_DSE_PSAPaddr(parm)\
	(void) fre_obj((char *) parm, _ZDSE_mod.md_dtab[_ZPSAPaddrDSE], &_ZDSE_mod, 1)
#endif
