/* @(#)83	1.3  src/tcpip/usr/lib/libisode/RONOT-types.h, isodelib7, tcpip411, GOLD410 4/5/93 13:35:16 */
/*
 * COMPONENT_NAME: (ISODELIB7) ISODE Libraries, Release 7
 *
 * FUNCTIONS: none
 *
 * ORIGINS: 60
 *
 * FILE:	src/tcpip/usr/lib/libisode/RONOT-types.h
 */

/* automatically generated by pepsy 6.0 #108 (oilers.netmgmt.austin.ibm.com), do not edit! */

#ifndef	_module_RONOT_defined_
#define	_module_RONOT_defined_

#ifndef	PEPSY_VERSION
#define	PEPSY_VERSION		2
#endif

#include <isode/psap.h>
#include <isode/pepsy.h>
#include <isode/pepsy/UNIV-types.h>

#include <isode/pepsy/RONOT_defs.h>

#define	type_RONOT_BindArgumentValue	PElement
#define	free_RONOT_BindArgumentValue	pe_free

#define	type_RONOT_BindResultValue	PElement
#define	free_RONOT_BindResultValue	pe_free

#define	type_RONOT_BindErrorValue	PElement
#define	free_RONOT_BindErrorValue	pe_free

#define	type_RONOT_UnBindArgumentValue	PElement
#define	free_RONOT_UnBindArgumentValue	pe_free

#define	type_RONOT_UnBindResultValue	PElement
#define	free_RONOT_UnBindResultValue	pe_free

#define	type_RONOT_UnBindErrorValue	PElement
#define	free_RONOT_UnBindErrorValue	pe_free
#endif
