/* @(#)97	1.3  src/tcpip/usr/lib/libisode/ROS-types.h, isodelib7, tcpip411, GOLD410 4/5/93 13:35:42 */
/*
 * COMPONENT_NAME: (ISODELIB7) ISODE Libraries, Release 7
 *
 * FUNCTIONS: free_ROS_Error free_ROS_GeneralProblem free_ROS_Invoke 
 *    free_ROS_InvokeIDType free_ROS_InvokeProblem free_ROS_OPDU 
 *    free_ROS_Operation free_ROS_ROERapdu free_ROS_ROIVapdu free_ROS_RORJapdu 
 *    free_ROS_RORSapdu free_ROS_ROSEapdus free_ROS_ReturnError 
 *    free_ROS_ReturnErrorProblem free_ROS_ReturnResult 
 *    free_ROS_ReturnResultProblem
 *
 * ORIGINS: 60
 *
 * FILE:	src/tcpip/usr/lib/libisode/ROS-types.h
 */

/* automatically generated by pepsy 6.0 #108 (oilers.netmgmt.austin.ibm.com), do not edit! */

#ifndef	_module_ROS_defined_
#define	_module_ROS_defined_

#ifndef	PEPSY_VERSION
#define	PEPSY_VERSION		2
#endif

#include <isode/psap.h>
#include <isode/pepsy.h>
#include <isode/pepsy/UNIV-types.h>

#include <isode/pepsy/ROS_defs.h>

#define	type_ROS_Reject	type_ROS_RORJapdu
#define	free_ROS_Reject	free_ROS_RORJapdu

struct type_ROS_Operation {
    integer     parm;
};
#define	free_ROS_Operation(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZOperationROS], &_ZROS_mod, 1)

struct type_ROS_Error {
    integer     parm;
};
#define	free_ROS_Error(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZErrorROS], &_ZROS_mod, 1)

struct type_ROS_ROSEapdus {
    int         offset;
#define	type_ROS_ROSEapdus_roiv__apdu	1
#define	type_ROS_ROSEapdus_rors__apdu	2
#define	type_ROS_ROSEapdus_roer__apdu	3
#define	type_ROS_ROSEapdus_rorj__apdu	4

    union {
        struct type_ROS_ROIVapdu *roiv__apdu;

        struct type_ROS_RORSapdu *rors__apdu;

        struct type_ROS_ROERapdu *roer__apdu;

        struct type_ROS_RORJapdu *rorj__apdu;
    }       un;
};
#define	free_ROS_ROSEapdus(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZROSEapdusROS], &_ZROS_mod, 1)

struct type_ROS_ROIVapdu {
    integer     optionals;
#define	opt_ROS_ROIVapdu_linked__ID (000000001)

    struct type_ROS_InvokeIDType *invokeID;

    integer     linked__ID;

    struct type_ROS_Operation *operation__value;

    PE      argument;
};
#define	free_ROS_ROIVapdu(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZROIVapduROS], &_ZROS_mod, 1)

struct type_ROS_InvokeIDType {
    integer     parm;
};
#define	free_ROS_InvokeIDType(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZInvokeIDTypeROS], &_ZROS_mod, 1)

struct type_ROS_RORSapdu {
    struct type_ROS_InvokeIDType *invokeID;

    struct element_ROS_1 {
        struct type_ROS_Operation *operation__value;

        PE      result;
    } *element_ROS_0;
};
#define	free_ROS_RORSapdu(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZRORSapduROS], &_ZROS_mod, 1)

struct type_ROS_ROERapdu {
    struct type_ROS_InvokeIDType *invokeID;

    struct type_ROS_Error *error__value;

    PE      parameter;
};
#define	free_ROS_ROERapdu(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZROERapduROS], &_ZROS_mod, 1)

struct type_ROS_RORJapdu {
    struct choice_ROS_0 {
        int         offset;
#define	choice_ROS_0_1	1
#define	choice_ROS_0_2	2

        union {
            struct type_ROS_InvokeIDType *choice_ROS_1;

            char    choice_ROS_2;
        }       un;
    } *invokeID;

    struct choice_ROS_3 {
        int         offset;
#define	choice_ROS_3_1	1
#define	choice_ROS_3_2	2
#define	choice_ROS_3_3	3
#define	choice_ROS_3_4	4

        union {
            struct type_ROS_GeneralProblem *choice_ROS_4;

            struct type_ROS_InvokeProblem *choice_ROS_5;

            struct type_ROS_ReturnResultProblem *choice_ROS_6;

            struct type_ROS_ReturnErrorProblem *choice_ROS_7;
        }       un;
    } *problem;
};
#define	free_ROS_RORJapdu(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZRORJapduROS], &_ZROS_mod, 1)

struct type_ROS_GeneralProblem {
    integer     parm;
#define	int_ROS_GeneralProblem_unrecognizedAPDU	0
#define	int_ROS_GeneralProblem_mistypedAPDU	1
#define	int_ROS_GeneralProblem_badlyStructuredAPDU	2
};
#define	free_ROS_GeneralProblem(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZGeneralProblemROS], &_ZROS_mod, 1)

struct type_ROS_InvokeProblem {
    integer     parm;
#define	int_ROS_InvokeProblem_duplicateInvocation	0
#define	int_ROS_InvokeProblem_unrecognizedOperation	1
#define	int_ROS_InvokeProblem_mistypedArgument	2
#define	int_ROS_InvokeProblem_resourceLimitation	3
#define	int_ROS_InvokeProblem_initiatorReleasing	4
#define	int_ROS_InvokeProblem_unrecognizedLinkedID	5
#define	int_ROS_InvokeProblem_linkedResponseUnexpected	6
#define	int_ROS_InvokeProblem_unexpectedChildOperation	7
};
#define	free_ROS_InvokeProblem(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZInvokeProblemROS], &_ZROS_mod, 1)

struct type_ROS_ReturnResultProblem {
    integer     parm;
#define	int_ROS_ReturnResultProblem_unrecognizedInvocation	0
#define	int_ROS_ReturnResultProblem_resultResponseUnexpected	1
#define	int_ROS_ReturnResultProblem_mistypedresult	2
};
#define	free_ROS_ReturnResultProblem(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZReturnResultProblemROS], &_ZROS_mod, 1)

struct type_ROS_ReturnErrorProblem {
    integer     parm;
#define	int_ROS_ReturnErrorProblem_unrecognizedInvocation	0
#define	int_ROS_ReturnErrorProblem_errorResponseUnexpected	1
#define	int_ROS_ReturnErrorProblem_unrecognizedError	2
#define	int_ROS_ReturnErrorProblem_unexpectedError	3
#define	int_ROS_ReturnErrorProblem_mistypedParameter	4
};
#define	free_ROS_ReturnErrorProblem(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZReturnErrorProblemROS], &_ZROS_mod, 1)

struct type_ROS_OPDU {
    int         offset;
#define	type_ROS_OPDU_1	1
#define	type_ROS_OPDU_2	2
#define	type_ROS_OPDU_3	3
#define	type_ROS_OPDU_4	4

    union {
        struct type_ROS_Invoke *choice_ROS_8;

        struct type_ROS_ReturnResult *choice_ROS_9;

        struct type_ROS_ReturnError *choice_ROS_10;

        struct type_ROS_Reject *choice_ROS_11;
    }       un;
};
#define	free_ROS_OPDU(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZOPDUROS], &_ZROS_mod, 1)

struct type_ROS_Invoke {
    integer     invokeID;

    struct type_ROS_Operation *element_ROS_2;

    PE      argument;
};
#define	free_ROS_Invoke(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZInvokeROS], &_ZROS_mod, 1)

struct type_ROS_ReturnResult {
    struct type_ROS_InvokeIDType *invokeID;

    PE      result;
};
#define	free_ROS_ReturnResult(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZReturnResultROS], &_ZROS_mod, 1)

struct type_ROS_ReturnError {
    integer     invokeID;

    struct type_ROS_Error *element_ROS_3;

    PE      parameter;
};
#define	free_ROS_ReturnError(parm)\
	(void) fre_obj((char *) parm, _ZROS_mod.md_dtab[_ZReturnErrorROS], &_ZROS_mod, 1)
#endif
