static char sccsid[] = "@(#)59	1.3  src/tcpip/usr/lib/libisode/UPEPY.c, isodelib7, tcpip411, GOLD410 4/5/93 13:37:11";
/*
 * COMPONENT_NAME: (ISODELIB7) ISODE Libraries, Release 7
 *
 * FUNCTIONS: build_UNIV_CharacterString build_UNIV_EXTERNAL 
 *    build_UNIV_GeneralString build_UNIV_GeneralisedTime 
 *    build_UNIV_GeneralizedTime build_UNIV_GraphicString build_UNIV_IA5String 
 *    build_UNIV_ISO646String build_UNIV_NumericString 
 *    build_UNIV_ObjectDescriptor build_UNIV_PrintableString 
 *    build_UNIV_T61String build_UNIV_TeletexString build_UNIV_UTCTime 
 *    build_UNIV_UniversalTime build_UNIV_VideotexString 
 *    build_UNIV_VisibleString parse_UNIV_CharacterString parse_UNIV_EXTERNAL 
 *    parse_UNIV_GeneralString parse_UNIV_GeneralisedTime 
 *    parse_UNIV_GeneralizedTime parse_UNIV_GraphicString parse_UNIV_IA5String 
 *    parse_UNIV_ISO646String parse_UNIV_NumericString 
 *    parse_UNIV_ObjectDescriptor parse_UNIV_PrintableString 
 *    parse_UNIV_T61String parse_UNIV_TeletexString parse_UNIV_UTCTime 
 *    parse_UNIV_UniversalTime parse_UNIV_VideotexString 
 *    parse_UNIV_VisibleString print_UNIV_CharacterString print_UNIV_EXTERNAL 
 *    print_UNIV_GeneralString print_UNIV_GeneralisedTime 
 *    print_UNIV_GeneralizedTime print_UNIV_GraphicString print_UNIV_IA5String 
 *    print_UNIV_ISO646String print_UNIV_NumericString 
 *    print_UNIV_ObjectDescriptor print_UNIV_PrintableString 
 *    print_UNIV_T61String print_UNIV_TeletexString print_UNIV_UTCTime 
 *    print_UNIV_UniversalTime print_UNIV_VideotexString 
 *    print_UNIV_VisibleString
 *
 * ORIGINS: 60
 *
 * FILE:	src/tcpip/usr/lib/libisode/UPEPY.c
 */

/* automatically generated by pepy 6.0 #86 (vikings.austin.ibm.com), do not edit! */

#include <isode/psap.h>

static char *pepyid = "pepy 6.0 #86 (vikings.austin.ibm.com) of Fri Mar 22 15:40:08 CST 1991";

#define	advise	PY_advise

void	advise ();

/* Generated from module UNIV */
# line 33 "../pepsy/UNIV.py"

#ifndef	lint
static char *rcsid = "$Header: /vikings/u/snmp/projects/harriet/RCS/src/tcpip/usr/lib/libisode/UPEPY.c,v 1.2 93/02/05 17:02:43 snmp Exp $";
#endif

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	build_UNIV_IA5String (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p0;
    int p0_len;

    p0 = buffer;
    if ((p0_len = len) == 0)
        p0_len = strlen (p0);
    if (p0 == NULLCP) {
        advise (NULLCP, "IA5String %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p0, p0_len, PE_CLASS_UNIV, 22)) == NULLPE) {
        advise (NULLCP, "IA5String: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.IA5String");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_IA5String (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p1;
    int p1_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.IA5String");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 22)) {
        advise (NULLCP, "IA5String %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p1 = prim2str (pe, &p1_len)) == NULLCP) {
        advise (NULLCP, "IA5String %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p1_len;
    if (buffer)
        *buffer = p1;
    else
        if (p1)
            free (p1);

    return OK;
}

/* ARGSUSED */

int	print_UNIV_IA5String (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p2;
    int p2_len;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 22)) {
        advise (NULLCP, "IA5String %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p2 = prim2str (pe, &p2_len)) == NULLCP) {
        advise (NULLCP, "IA5String %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p2_len;
    if (buffer)
        *buffer = p2;
    else
        if (p2)
            free (p2);

    return OK;
}

/* ARGSUSED */

int	build_UNIV_NumericString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_IA5String (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;
    (*pe) -> pe_class = PE_CLASS_UNIV;
    (*pe) -> pe_id = 18;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.NumericString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_NumericString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.NumericString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 18)) {
        advise (NULLCP, "NumericString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (parse_UNIV_IA5String (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_NumericString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 18)) {
        advise (NULLCP, "NumericString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (print_UNIV_IA5String (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_PrintableString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_IA5String (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;
    (*pe) -> pe_class = PE_CLASS_UNIV;
    (*pe) -> pe_id = 19;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.PrintableString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_PrintableString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.PrintableString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 19)) {
        advise (NULLCP, "PrintableString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (parse_UNIV_IA5String (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_PrintableString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 19)) {
        advise (NULLCP, "PrintableString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (print_UNIV_IA5String (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_T61String (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p3;
    int p3_len;

    p3 = buffer;
    if ((p3_len = len) == 0)
        p3_len = strlen (p3);
    if (p3 == NULLCP) {
        advise (NULLCP, "T61String %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p3, p3_len, PE_CLASS_UNIV, 20)) == NULLPE) {
        advise (NULLCP, "T61String: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.T61String");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_T61String (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p4;
    int p4_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.T61String");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 20)) {
        advise (NULLCP, "T61String %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p4 = prim2str (pe, &p4_len)) == NULLCP) {
        advise (NULLCP, "T61String %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p4_len;
    if (buffer)
        *buffer = p4;
    else
        if (p4)
            free (p4);

    return OK;
}

/* ARGSUSED */

int	print_UNIV_T61String (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p5;
    int p5_len;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 20)) {
        advise (NULLCP, "T61String %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p5 = prim2str (pe, &p5_len)) == NULLCP) {
        advise (NULLCP, "T61String %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p5_len;
    if (buffer)
        *buffer = p5;
    else
        if (p5)
            free (p5);

    return OK;
}

/* ARGSUSED */

int	build_UNIV_TeletexString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_T61String (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.TeletexString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_TeletexString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.TeletexString");
#endif

    if (parse_UNIV_T61String (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_TeletexString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (print_UNIV_T61String (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_VideotexString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p6;
    int p6_len;

    p6 = buffer;
    if ((p6_len = len) == 0)
        p6_len = strlen (p6);
    if (p6 == NULLCP) {
        advise (NULLCP, "VideotexString %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p6, p6_len, PE_CLASS_UNIV, 21)) == NULLPE) {
        advise (NULLCP, "VideotexString: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.VideotexString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_VideotexString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p7;
    int p7_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.VideotexString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 21)) {
        advise (NULLCP, "VideotexString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p7 = prim2str (pe, &p7_len)) == NULLCP) {
        advise (NULLCP, "VideotexString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p7_len;
    if (buffer)
        *buffer = p7;
    else
        if (p7)
            free (p7);

    return OK;
}

/* ARGSUSED */

int	print_UNIV_VideotexString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p8;
    int p8_len;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 21)) {
        advise (NULLCP, "VideotexString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p8 = prim2str (pe, &p8_len)) == NULLCP) {
        advise (NULLCP, "VideotexString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p8_len;
    if (buffer)
        *buffer = p8;
    else
        if (p8)
            free (p8);

    return OK;
}

/* ARGSUSED */

int	build_UNIV_GeneralizedTime (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_VisibleString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;
    (*pe) -> pe_class = PE_CLASS_UNIV;
    (*pe) -> pe_id = 24;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.GeneralizedTime");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_GeneralizedTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.GeneralizedTime");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 24)) {
        advise (NULLCP, "GeneralizedTime %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (parse_UNIV_VisibleString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_GeneralizedTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 24)) {
        advise (NULLCP, "GeneralizedTime %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (print_UNIV_VisibleString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_GeneralisedTime (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_GeneralizedTime (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.GeneralisedTime");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_GeneralisedTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.GeneralisedTime");
#endif

    if (parse_UNIV_GeneralizedTime (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_GeneralisedTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (print_UNIV_GeneralizedTime (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_UTCTime (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_VisibleString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;
    (*pe) -> pe_class = PE_CLASS_UNIV;
    (*pe) -> pe_id = 23;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.UTCTime");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_UTCTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.UTCTime");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 23)) {
        advise (NULLCP, "UTCTime %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (parse_UNIV_VisibleString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_UTCTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 23)) {
        advise (NULLCP, "UTCTime %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (print_UNIV_VisibleString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_UniversalTime (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_UTCTime (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.UniversalTime");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_UniversalTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.UniversalTime");
#endif

    if (parse_UNIV_UTCTime (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_UniversalTime (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (print_UNIV_UTCTime (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_GraphicString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p9;
    int p9_len;

    p9 = buffer;
    if ((p9_len = len) == 0)
        p9_len = strlen (p9);
    if (p9 == NULLCP) {
        advise (NULLCP, "GraphicString %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p9, p9_len, PE_CLASS_UNIV, 25)) == NULLPE) {
        advise (NULLCP, "GraphicString: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.GraphicString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_GraphicString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p10;
    int p10_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.GraphicString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 25)) {
        advise (NULLCP, "GraphicString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p10 = prim2str (pe, &p10_len)) == NULLCP) {
        advise (NULLCP, "GraphicString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p10_len;
    if (buffer)
        *buffer = p10;
    else
        if (p10)
            free (p10);

    return OK;
}

/* ARGSUSED */

int	print_UNIV_GraphicString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p11;
    int p11_len;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 25)) {
        advise (NULLCP, "GraphicString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p11 = prim2str (pe, &p11_len)) == NULLCP) {
        advise (NULLCP, "GraphicString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p11_len;
    if (buffer)
        *buffer = p11;
    else
        if (p11)
            free (p11);

    return OK;
}

/* ARGSUSED */

int	build_UNIV_VisibleString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p12;
    int p12_len;

    p12 = buffer;
    if ((p12_len = len) == 0)
        p12_len = strlen (p12);
    if (p12 == NULLCP) {
        advise (NULLCP, "VisibleString %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p12, p12_len, PE_CLASS_UNIV, 26)) == NULLPE) {
        advise (NULLCP, "VisibleString: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.VisibleString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_VisibleString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p13;
    int p13_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.VisibleString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 26)) {
        advise (NULLCP, "VisibleString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p13 = prim2str (pe, &p13_len)) == NULLCP) {
        advise (NULLCP, "VisibleString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p13_len;
    if (buffer)
        *buffer = p13;
    else
        if (p13)
            free (p13);

    return OK;
}

/* ARGSUSED */

int	print_UNIV_VisibleString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p14;
    int p14_len;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 26)) {
        advise (NULLCP, "VisibleString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p14 = prim2str (pe, &p14_len)) == NULLCP) {
        advise (NULLCP, "VisibleString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p14_len;
    if (buffer)
        *buffer = p14;
    else
        if (p14)
            free (p14);

    return OK;
}

/* ARGSUSED */

int	build_UNIV_ISO646String (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_VisibleString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.ISO646String");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_ISO646String (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.ISO646String");
#endif

    if (parse_UNIV_VisibleString (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_ISO646String (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (print_UNIV_VisibleString (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	build_UNIV_GeneralString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p15;
    int p15_len;

    p15 = buffer;
    if ((p15_len = len) == 0)
        p15_len = strlen (p15);
    if (p15 == NULLCP) {
        advise (NULLCP, "GeneralString %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p15, p15_len, PE_CLASS_UNIV, 27)) == NULLPE) {
        advise (NULLCP, "GeneralString: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.GeneralString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_GeneralString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p16;
    int p16_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.GeneralString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 27)) {
        advise (NULLCP, "GeneralString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p16 = prim2str (pe, &p16_len)) == NULLCP) {
        advise (NULLCP, "GeneralString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p16_len;
    if (buffer)
        *buffer = p16;
    else
        if (p16)
            free (p16);

    return OK;
}

/* ARGSUSED */

int	print_UNIV_GeneralString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p17;
    int p17_len;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 27)) {
        advise (NULLCP, "GeneralString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p17 = prim2str (pe, &p17_len)) == NULLCP) {
        advise (NULLCP, "GeneralString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p17_len;
    if (buffer)
        *buffer = p17;
    else
        if (p17)
            free (p17);

    return OK;
}

/* ARGSUSED */

int	build_UNIV_CharacterString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p18;
    int p18_len;

    p18 = buffer;
    if ((p18_len = len) == 0)
        p18_len = strlen (p18);
    if (p18 == NULLCP) {
        advise (NULLCP, "CharacterString %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p18, p18_len, PE_CLASS_UNIV, 28)) == NULLPE) {
        advise (NULLCP, "CharacterString: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.CharacterString");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_CharacterString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p19;
    int p19_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.CharacterString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 28)) {
        advise (NULLCP, "CharacterString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p19 = prim2str (pe, &p19_len)) == NULLCP) {
        advise (NULLCP, "CharacterString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p19_len;
    if (buffer)
        *buffer = p19;
    else
        if (p19)
            free (p19);

    return OK;
}

/* ARGSUSED */

int	print_UNIV_CharacterString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p20;
    int p20_len;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 28)) {
        advise (NULLCP, "CharacterString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p20 = prim2str (pe, &p20_len)) == NULLCP) {
        advise (NULLCP, "CharacterString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p20_len;
    if (buffer)
        *buffer = p20;
    else
        if (p20)
            free (p20);

    return OK;
}

/* ARGSUSED */

int	build_UNIV_EXTERNAL (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p21_z = NULLPE;
    register PE *p21 = &p21_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, 8)) == NULLPE) {
        advise (NULLCP, "EXTERNAL: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }
    (*p21) = NULLPE;

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p21) = NULLPE;

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p21) = NULLPE;

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p21) = NULLPE;

    {	/* encoding */

#ifdef DEBUG
        (void) testdebug ((*p21), "encoding");
#endif

    }

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.EXTERNAL");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_EXTERNAL (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p22;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.EXTERNAL");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 8)) {
        advise (NULLCP, "EXTERNAL %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p22 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "EXTERNAL %s%s", PEPY_ERR_BAD_SEQ,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p22;

    {
        register PE p23;

        if ((p23 = first_member (pe)) != NULLPE
                && PE_ID (p23 -> pe_class, p23 -> pe_id)
                        != PE_ID (PE_CLASS_UNIV, 6))
            p23 = NULLPE;
        if (p23 != NULLPE) {
            p22 = p23;

            {	/* direct-reference */
#ifdef DEBUG
                (void) testdebug (p23, "direct-reference");
#endif

                if (p23 -> pe_class != PE_CLASS_UNIV
                        || p23 -> pe_form != PE_FORM_PRIM
                        || p23 -> pe_id != PE_PRIM_OID) {
                    advise (NULLCP, "direct-reference bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p23 -> pe_class], p23 -> pe_form, p23 -> pe_id);
                    return NOTOK;
                }

                if (prim2oid (p23) == NULLOID) {
                    advise (NULLCP, "direct-reference %s%s", PEPY_ERR_BAD_OID,
                            pe_error (p23 -> pe_errno));
                    return NOTOK;
                }
            }
        }
    }

    {
        register PE p24;

        if ((p24 = (pe != p22 ? next_member (pe, p22) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p24 -> pe_class, p24 -> pe_id)
                        != PE_ID (PE_CLASS_UNIV, 2))
            p24 = NULLPE;
        if (p24 != NULLPE) {
            p22 = p24;

            {	/* indirect-reference */
#ifdef DEBUG
                (void) testdebug (p24, "indirect-reference");
#endif

                if (p24 -> pe_class != PE_CLASS_UNIV
                        || p24 -> pe_form != PE_FORM_PRIM
                        || p24 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "indirect-reference bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p24 -> pe_class], p24 -> pe_form, p24 -> pe_id);
                    return NOTOK;
                }

                if (prim2num (p24) == NOTOK
                        && p24 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "indirect-reference %s%s", PEPY_ERR_BAD_INTEGER,
                            pe_error (p24 -> pe_errno));
                    return NOTOK;
                }
            }
        }
        else {
            /* set default here using yp -> yp_default */
        }

    }

    {
        register PE p25;

        if ((p25 = (pe != p22 ? next_member (pe, p22) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p25 -> pe_class, p25 -> pe_id)
                        != PE_ID (PE_CLASS_UNIV, 7))
            p25 = NULLPE;
        if (p25 != NULLPE) {
            p22 = p25;

            {	/* data-value-descriptor */
#ifdef DEBUG
                (void) testdebug (p25, "data-value-descriptor");
#endif

                if (parse_UNIV_ObjectDescriptor (p25, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                    return NOTOK;
            }
        }
    }

    {
        register PE p26;

        if ((p26 = (pe != p22 ? next_member (pe, p22) : first_member (pe))) != NULLPE) {
            p22 = p26;

            {	/* encoding */
#ifdef DEBUG
                (void) testdebug (p26, "encoding");
#endif

                switch (PE_ID (p26 -> pe_class, p26 -> pe_id)) {
                    case PE_ID (PE_CLASS_CONT, 0):	/* single-ASN1-type */
                        {
                            register PE p27 = p26;

                            {	/* single-ASN1-type TAG PULLUP */
                                register PE p28;

                                if ((p28 = prim2set (p27)) == NULLPE) {
                                    advise (NULLCP, "single-ASN1-type %ssingle-ASN1-type: %s", PEPY_ERR_BAD,
                                            pe_error (p27 -> pe_errno));
                                    return NOTOK;
                                }
                                if (p28 -> pe_cardinal != 1) {
                                    advise (NULLCP, "single-ASN1-type %s single-ASN1-type: %d", PEPY_ERR_TOO_MANY_TAGGED,
                                            p28 -> pe_cardinal);
                                    return NOTOK;
                                }
                                p27 = first_member (p28);
                            }
                            {
#ifdef DEBUG
                                (void) testdebug (p27, "single-ASN1-type");
#endif

                            }
                        }
                        break;
                    case PE_ID (PE_CLASS_CONT, 1):	/* octet-aligned */
                        {
#ifdef DEBUG
                            (void) testdebug (p26, "octet-aligned");
#endif

                        }
                        break;
                    case PE_ID (PE_CLASS_CONT, 2):	/* arbitrary */
                        {
#ifdef DEBUG
                            (void) testdebug (p26, "arbitrary");
#endif

                            if (prim2bit (p26) == NULLPE) {
                                advise (NULLCP, "arbitrary %s%s", PEPY_ERR_BAD_BITS,
                                        pe_error (p26 -> pe_errno));
                                return NOTOK;
                            }
                        }
                        break;

                    default:
                        advise (NULLCP, "encoding %s%s/%d/0x%x", PEPY_ERR_UNKNOWN_CHOICE,
                                pe_classlist[p26 -> pe_class], p26 -> pe_form, p26 -> pe_id);
                        return NOTOK;
                }
            }
        }
        else {
            advise (NULLCP, "EXTERNAL %sencoding element", PEPY_ERR_MISSING);
            return NOTOK;
        }

    }


    if (pe -> pe_cardinal > 4) {
        advise (NULLCP, "EXTERNAL %s(4): %d", PEPY_ERR_TOO_MANY_ELEMENTS,
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_UNIV_EXTERNAL (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p29;

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 8)) {
        advise (NULLCP, "EXTERNAL %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p29 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "EXTERNAL %s%s", PEPY_ERR_BAD_SEQ,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p29;

    vpush ();
    {
        register PE p30;

        if ((p30 = first_member (pe)) != NULLPE
                && PE_ID (p30 -> pe_class, p30 -> pe_id)
                        != PE_ID (PE_CLASS_UNIV, 6))
            p30 = NULLPE;
        if (p30 != NULLPE) {
            p29 = p30;

            {	/* direct-reference */
                register OID p31;

                if (p30 -> pe_class != PE_CLASS_UNIV
                        || p30 -> pe_form != PE_FORM_PRIM
                        || p30 -> pe_id != PE_PRIM_OID) {
                    advise (NULLCP, "direct-reference bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p30 -> pe_class], p30 -> pe_form, p30 -> pe_id);
                    return NOTOK;
                }

                vname ("direct-reference");
                if ((p31 = prim2oid (p30)) == NULLOID) {
                    advise (NULLCP, "direct-reference %s%s", PEPY_ERR_BAD_OID,
                            pe_error (p30 -> pe_errno));
                    return NOTOK;
                }
                vprint ("%s", oid2ode (p31));
            }
        }
    }

    {
        register PE p32;

        if ((p32 = (pe != p29 ? next_member (pe, p29) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p32 -> pe_class, p32 -> pe_id)
                        != PE_ID (PE_CLASS_UNIV, 2))
            p32 = NULLPE;
        if (p32 != NULLPE) {
            p29 = p32;

            {	/* indirect-reference */
                register integer p33;

                if (p32 -> pe_class != PE_CLASS_UNIV
                        || p32 -> pe_form != PE_FORM_PRIM
                        || p32 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "indirect-reference bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p32 -> pe_class], p32 -> pe_form, p32 -> pe_id);
                    return NOTOK;
                }

                vname ("indirect-reference");
                if ((p33 = prim2num (p32)) == NOTOK
                        && p32 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "indirect-reference %s%s", PEPY_ERR_BAD_INTEGER,
                            pe_error (p32 -> pe_errno));
                    return NOTOK;
                }
                vprint ("%d", p33);
            }
        }
        else {
            /* set default here using yp -> yp_default */
        }

    }

    {
        register PE p34;

        if ((p34 = (pe != p29 ? next_member (pe, p29) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p34 -> pe_class, p34 -> pe_id)
                        != PE_ID (PE_CLASS_UNIV, 7))
            p34 = NULLPE;
        if (p34 != NULLPE) {
            p29 = p34;

            {	/* data-value-descriptor */
                vname ("data-value-descriptor");
                if (print_UNIV_ObjectDescriptor (p34, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                    return NOTOK;
            }
        }
    }

    {
        register PE p35;

        if ((p35 = (pe != p29 ? next_member (pe, p29) : first_member (pe))) != NULLPE) {
            p29 = p35;

            {	/* encoding */
                vname ("encoding");
                vpush ();
                switch (PE_ID (p35 -> pe_class, p35 -> pe_id)) {
                    case PE_ID (PE_CLASS_CONT, 0):	/* single-ASN1-type */
                        {
                            register PE p36 = p35;

                            {	/* single-ASN1-type TAG PULLUP */
                                register PE p37;

                                if ((p37 = prim2set (p36)) == NULLPE) {
                                    advise (NULLCP, "single-ASN1-type %ssingle-ASN1-type: %s", PEPY_ERR_BAD,
                                            pe_error (p36 -> pe_errno));
                                    return NOTOK;
                                }
                                if (p37 -> pe_cardinal != 1) {
                                    advise (NULLCP, "single-ASN1-type %s single-ASN1-type: %d", PEPY_ERR_TOO_MANY_TAGGED,
                                            p37 -> pe_cardinal);
                                    return NOTOK;
                                }
                                p36 = first_member (p37);
                            }
                            {
                                vname ("single-ASN1-type");
                                vunknown (p36);
                            }
                        }
                        break;
                    case PE_ID (PE_CLASS_CONT, 1):	/* octet-aligned */
                        {
                            vname ("octet-aligned");
                            vstring (p35);
                        }
                        break;
                    case PE_ID (PE_CLASS_CONT, 2):	/* arbitrary */
                        {
                            register PE p38;

                            vname ("arbitrary");
                            if ((p38 = prim2bit (p35)) == NULLPE) {
                                advise (NULLCP, "arbitrary %s%s", PEPY_ERR_BAD_BITS,
                                        pe_error (p35 -> pe_errno));
                                return NOTOK;
                            }
                            if (p38 -> pe_nbits < 128)
                                vprint ("%s", bit2str (p38, "\020"));
                            else
                                vunknown (p38);
                        }
                        break;

                    default:
                        advise (NULLCP, "encoding %s%s/%d/0x%x", PEPY_ERR_UNKNOWN_CHOICE,
                                pe_classlist[p35 -> pe_class], p35 -> pe_form, p35 -> pe_id);
                        return NOTOK;
                }
                vpop ();
            }
        }
        else {
            advise (NULLCP, "EXTERNAL %sencoding element", PEPY_ERR_MISSING);
            return NOTOK;
        }

    }

    vpop ();

    if (pe -> pe_cardinal > 4) {
        advise (NULLCP, "EXTERNAL %s(4): %d", PEPY_ERR_TOO_MANY_ELEMENTS,
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	build_UNIV_ObjectDescriptor (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_UNIV_GraphicString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;
    (*pe) -> pe_class = PE_CLASS_UNIV;
    (*pe) -> pe_id = 7;

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.ObjectDescriptor");
#endif


    return OK;
}

/* ARGSUSED */

int	parse_UNIV_ObjectDescriptor (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "UNIV.ObjectDescriptor");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 7)) {
        advise (NULLCP, "ObjectDescriptor %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (parse_UNIV_GraphicString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_UNIV_ObjectDescriptor (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 7)) {
        advise (NULLCP, "ObjectDescriptor %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if (print_UNIV_GraphicString (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}
# line 145 "../pepsy/UNIV.py"


#ifndef PEPSY_VERSION

PEPYPARM NullParm = (PEPYPARM) 0;
#endif

