# @(#)09	1.4  src/rspc/usr/lib/methods/cfgkbd_isa/Makefile, rspccfg, rspc41J, 9509A_all 2/14/95 13:18:57
# COMPONENT_NAME: rspccfg
#
# FUNCTIONS: N/A
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST       = cfgkbd_isa
IDIR        = /usr/lib/methods/

SCRIPTS		= cfgkbd_isa

.include <${RULES_MK}>
