# @(#)25	1.1  com/cmd/usr.etc/yp/makefile, cmdnfs, nfs410 2/23/93 10:34:38
# COMPONENT_NAME: (CMDNFS) Network File System Commands
# 
# FUNCTIONS: 
#
# ORIGINS: 27 
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# 
.include	<${MAKETOP}nfs/NFS.mk>

DATAFILES	=	\
	updaters	\
	Makefile

MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}
ILIST		= ${DATAFILES}
IDIR		= /var/yp/
NOUPDATE_LIST 	= Makefile

.include <${RULES_MK}>
