# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= instfix
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= instfix
IDIR		= /usr/sbin/

INCFLAGS	= -I../messages -I../include

OFILES		= \
	instfix.o 

LIBS		= -linulib -lodm -lswvpd

.include <${RULES_MK}>
