# @(#)75        1.6  src/rspc/kernext/isa/Makefile, Makefiles, rspc41J, 9510A 2/16/95 11:50:58
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS         = fd isakbd isamouse tty ppa itok ient dartic_isa ide

.include <${RULES_MK}>
