# @(#)83	1.6  src/tcpip/usr/include/isode/pepsy/Makefile, tcpip, tcpip411, GOLD410 7/7/94 16:31:43
# 
# COMPONENT_NAME: SNMP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#


INCLUDES		= \
			ACS_defs.h ACS_pre_defs.h \
			UNIV-types.h UNIV_defs.h UNIV_pre_defs.h \
			PS_defs.h PS_pre_defs.h DASE_defs.h DASE_pre_defs.h \
			DSE_defs.h DSE_pre_defs.h OACS_defs.h OACS_pre_defs.h \
			RONOT_defs.h RONOT_pre_defs.h ROS_defs.h \
			ROS_pre_defs.h RTS_defs.h RTS_pre_defs.h \
			SMI-types.h SMI_defs.h SMI_pre_defs.h SNMP-types.h \
			SNMP_defs.h SNMP_pre_defs.h SMUX-types.h \
			SMUX_defs.h SMUX_pre_defs.h

ILIST			= \
			ACS_defs.h ACS_pre_defs.h DSE_defs.h DSE_pre_defs.h \
			UNIV-types.h UNIV_defs.h UNIV_pre_defs.h SMI-types.h \
			SMI_defs.h SMI_pre_defs.h SNMP-types.h SNMP_defs.h \
			SNMP_pre_defs.h SMUX-types.h SMUX_defs.h \
			SMUX_pre_defs.h

IDIR			= /usr/include/isode/pepsy/
IMODE			= 644

.include <${RULES_MK}>
