# @(#)97	1.8  src/tenplus/lib/Makefile, tenplus, tenplus411, GOLD410 10/28/93 13:02:04
#
# COMPONENT_NAME: (TENPLUS) INed Editor
#
# FUNCTIONS:
#
# ORIGINS:  9, 10, 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
# 
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

SUBDIRS = prf util window short obj

.include <${RULES_MK}>

