#
#
#
#   ORIGINS: 27
#
#
#
#
.include	<${MAKETOP}nfs/NFS.mk>

VPATH		= ${MAKETOP}nfs/msghdr

MSGHDRS		= cmdnfs_msg.h
INCLUDES	= ${MSGHDRS}

EXPINC_SUBDIRS          = lock nfs rpc rpcsvc

SUBDIRS			= lock nfs rpc rpcsvc


IDIR	= /kernel/include/

.include <${RULES_MK}>
