# @(#)43        1.1  src/bos/usr/lpp/perfagent/Makefile, lockstat, perf411, GOLD410 3/2/94 11:18:35

#
# COMPONENT_NAME:  PERFAGENT
#
# FUNCTIONS:
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


#
# LEVEL 1,  5 Years Bull Confidential Information
#


SUBDIRS         = lockstat

.include <${RULES_MK}>




