# @(#) 65 1.7 src/bos/usr/sys/inst.data/sys_bundles/Makefile, pkg, bos41J, 9522A_all 5/30/95 18:09:14
# COMPONENT_NAME: pkg
#
# FUNCTIONS: Makefile for bundle files
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993,1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= BOS.autoi \
			GOS.autoi \
			ASCII.autoi \
			Hdwr-Diag.def \
			App-Dev.def \
			Client.def \
			GOS.adt \
			GOS.client \
			GOS.server \
			Pers-Prod.bnd \
			Server.def \
			DCE-Client.def


IDIR		= /usr/sys/inst.data/sys_bundles/


.include <${RULES_MK}>
