# @(#)05	1.1  src/rspc/usr/lib/boot/softros/lib/Makefile, rspc_softros, rspc411, GOLD410 4/18/94 15:44:21
#
#   COMPONENT_NAME: RSPC_SOFTROS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS	= libc libstand

SUBDIRS		= libc libstand

.include <${RULES_MK}>

