# @(#)16        1.2  src/bos/usr/sbin/savecore/Makefile, Makefiles, bos411, 9428A410j 3/2/93 17:18:48
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= savecore copycore
MSGHDRS		= savecr_msg.h
CATFILES	= savecr.cat
HFILES		= ${MSGHDRS}

ILIST		= savecore copycore
IDIR		= /usr/sbin/

LIBS            = -lras -lcfg -lodm


.include <${RULES_MK}>
