# @(#)68 1.2 src/bos/usr/sbin/keycfg/Makefile, dsaukey, bos41B, 412_41B_sync 12/21/94 06:48:19

# COMPONENT_NAME: DSAUKEY
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# LEVEL 1,5 Years Bull Confidential Information
#

PROGRAMS	= keycfg
MSGHDRS		= keycfg_msg.h
CATFILES	= keycfg.cat
HFILES		= ${MSGHDRS}

LIBS		= -lodm -lcfg

ILIST		= keycfg
IDIR		= /usr/sbin/


.include <${RULES_MK}>
