# 
#
# ORIGINS: 27 
#
#
# 

SCRIPTS 	=	\
	mknfs		\
	rmnfs		\
	chnfs		\
	chypdom		\
	lsnfsexp	\
	mknfsexp	\
	rmnfsexp	\
	lsnfsmnt	\
	mknfsmnt	\
	rmnfsmnt	\
	lsmaster	\
	mkmaster	\
	mkslave		\
	mkclient	\
	rmyp		\
	mkkeyserv	\
	rmkeyserv	\
	mkhanfs		\
	rmhanfs		

ILIST		= ${SCRIPTS}
IDIR		= /usr/sbin/

.include <${RULES_MK}>

