# @(#)88        1.1  src/bos/usr/sbin/fsck/Makefile, cmdfs, bos411, 9428A410j 8/5/92 17:50:28
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= fsck
MSGHDRS		= fsck_msg.h
CATFILES	= fsck.cat
HFILES		= ${MSGHDRS}

ILIST		= fsck
IDIR		= /usr/sbin/

INCLUDES	= fsck.h
fsck.h_IDIR	= /usr/include/

LIBS		= -lIN

.include <${RULES_MK}>
