# @(#)79	1.5  src/tcpip/usr/include/Makefile, tcpip, tcpip411, GOLD410 3/18/94 13:10:25
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 10  26  27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

VPATH                   = ${TARGET_MACHINE}
SUBDIRS                 = isode

EXPINC_SUBDIRS  	= ${SUBDIRS}

INCLUDES		= cfg04.h inetodm.h libffdb.h libsmit.h \
			libsrc.h lm.h ocsvhost.h smitcfg.h tcpip_audit.h \
			if_fddi.h if_op.h if_fcs.h ocsadmin.h

IDIR                    = /usr/include/
ILIST                   = tcpip_audit.h
IMODE                   = 644

.include <${RULES_MK}>
