# @(#)20	1.1  src/bos/usr/lpp/zhls/dict/Makefile, ils-zh_CN, bos41B, 9504A 12/21/94 09:47:45
#
#   COMPONENT_NAME: ils-zh_CN
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
ILIST   = abcsysdict.cwd_t ensysdict pysysdict_cns pysysdict_gb tjsysdict \
	abcsysdict.cwd_s abcsysdict.ovl lesysdict pysysdict_comm pysysdict_jk

IDIR    = /usr/lpp/zhls/dict/

.include <${RULES_MK}>
