# @(#)71	1.2  src/rspc/kernext/disp/pcihga/inc/Makefile, pcihga, rspc411, GOLD410 5/24/94 16:39:22
#
#   COMPONENT_NAME: pcihga
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

EXPDIR          = /kernel/include/graphics/

INCLUDES        = hgadds.h hga_reg.h hga_regval.h \
		hga.h hgaddf.h hgaldat.h

.include <${RULES_MK}>


