# @(#)85        1.1  src/bos/usr/sbin/lsvfs/Makefile, cmdfs, bos411, 9428A410j 8/5/92 17:49:31
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= lsvfs
MSGHDRS		= lsvfs_msg.h
CATFILES	= lsvfs.cat
HFILES		= ${MSGHDRS}

ILIST		= lsvfs
IDIR		= /usr/sbin/

LIBS		= -lPW

.include <${RULES_MK}>
