# @(#)46	1.1  src/tcpip/usr/sbin/chsubserver/Makefile, tcpinet, tcpip411, GOLD410 3/19/93 10:26:47
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 27 
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS			= chsubserver
MSGHDRS			= chsubserver_msg.h
CATFILES		= chsubserver.cat

ILIST                   = chsubserver
IDIR                    = /usr/sbin/

.include <${RULES_MK}>
