# @(#)77        1.4  src/rspc/usr/include/Makefile, Makefiles, rspc41J, 9510A 3/8/95 18:27:35
#
#   COMPONENT_NAME: MAKEFILES
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS  = sys

SUBDIRS = sys

IDIR            = /usr/include/
DATAFILES       = pmlib.h
INCLUDES        = pmlib.h
ILIST           = ${DATAFILES}

.include <${RULES_MK}>
