# @(#)62        1.2  src/bos/usr/sbin/mkproto/Makefile, cmdfiles, bos411, 9428A410j 6/9/93 10:11:36
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= mkproto
MSGHDRS		= mkproto_msg.h
CATFILES	= mkproto.cat

ILIST		= mkproto
IDIR		= /usr/sbin/

.include <${RULES_MK}>

mkproto: mkproto_msg.h
