$ @(#)59        1.3.1.2  src/bos/usr/sbin/mkproto/mkproto.msg, cmdfiles, bos411, 9428A410j 9/1/93 16:47:41
$
$ COMPONENT_NAME: (CMDFILES) commands that manipulate files 
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 367 - 369 reserved for this file.
$
$set MS_MKPROTO
$ message for the mkproto.sh shell script

1 "Usage: mkproto Special Proto"
$ Do not translate mkproto.
$ Special can a block device name, raw device name or file system name.
$ Proto is the name of a prototype file.
