# @(#)78	1.3  src/tcpip/usr/ccs/lib/libinetodm/Makefile, tcpip, tcpip411, GOLD410 2/15/93 14:38:53
# COMPONENT_NAME: TCPIP - OCS Utility library
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES		= libinetodm.a

EXPLIB_TARGETS		= export_libinetodm.a

ILIST			= libinetodm.a
IDIR			= /usr/ccs/lib/
IMODE			= 644

OFILES			= inetodm.o

.include <${RULES_MK}>
