# @(#)47        1.1  src/bos/usr/sbin/strinfo/Makefile, cmdpse, bos411, 9428A410j 8/5/92 17:59:39
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/kernext/exp

PROGRAMS	= strinfo
MSGHDRS		= strinfo_msg.h
CATFILES	= strinfo.cat
HFILES		= ${MSGHDRS}

ILIST		= strinfo
IDIR		= /usr/sbin/

strinfo_IMPORTS	= -bI:pse_int.exp

.include <${RULES_MK}>
