# @(#)48  1.1 src/bos/usr/sbin/nddstat/fddistat/Makefile, nddstat, bos411, 9428A410j  3/7/94  10:53:18
#
#   COMPONENT_NAME: NDDSTAT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
VPATH		= ../common

PROGRAMS	= fddistat
MSGHDRS         = fddistat_msg.h
CATFILES        = fddistat.cat
HFILES          = ${MSGHDRS}

ILIST		= fddistat
IDIR		= /usr/sbin/

OFILES		= main.o fddistat.o

.include <${RULES_MK}>
