# @(#)65	1.3  src/rspc/kernext/pcmcia/Makefile, Makefiles, rspc411, 9437A411a 9/7/94 19:37:39
#
#   COMPONENT_NAME: Makefiles
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= ssisa cs tok ent tty

.include <${RULES_MK}>
