# @(#)93        1.2  src/bos/usr/sbin/survd/Makefile, cmdmp, bos411, 9428A410j 3/21/94 04:36:19

# COMPONENT_NAME: (CMDMP)
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# LEVEL 1,5 Years Bull Confidential Information
#

PROGRAMS	= survd
MSGHDRS		= survd_msg.h
CATFILES	= survd.cat
HFILES		= ${MSGHDRS}

ILIST		= survd
IDIR		= /usr/sbin/

.include <${RULES_MK}>
