# 
# 
#
# ORIGINS: 27 
#
#
# 

SCRIPTS		=		\
	INSTALL		\
	MAKEDEV		\
	convert_to_hex	\
	create_root		\
	verify_tapevol_arch	\
	extracting		\
	fix_bootparams	\
	make_dirs		\
	setup_exec		\
	setup_client


ILIST =		\
	mkfile		\
	opt_software	\
	xdrtoc \
	${SCRIPTS}

IDIR		= /usr/lpp/nfs/sun_diskless/

.include <${RULES_MK}>
