# @(#)14        1.1  src/xlf/usr/lpp/xlf/Makefile, fortran, xlf411, GOLD410 6/8/93 10:39:21
#
#   COMPONENT_NAME: (Fortran)  Fortran Compiler
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= bin

.include <${RULES_MK}>
