# @(#)96        1.1  src/bos/usr/sbin/open_door/Makefile, cmdcfg, bos412, 9445C412b 11/2/94 03:23:34
#
# COMPONENT_NAME: (CMDCFG)
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# LEVEL 1,5 Years Bull Confidential Information
#

PROGRAMS        = open_door 
MSGHDRS         = open_door_msg.h
CATFILES        = open_door.cat
HFILES          = ${MSGHDRS}

ILIST           = open_door
IDIR            = /usr/sbin/

.include <${RULES_MK}>

