# @(#)05  1.1  src/rspc/kernext/disp/pciwfg/inc/Makefile, pciwfg, rspc411, 9434B411a 8/24/94 07:41:22
# Makefile
#
#   COMPONENT_NAME: (PCIWFG) WD90C24A2 PCI Graphics Adapter Device Driver
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPDIR          = /kernel/include/graphics/

INCLUDES        = wfgdds.h wfg_reg.h wfg_regval.h \
		  wfg.h wfgddf.h wfgldat.h

.include <${RULES_MK}>
