# @(#)51        1.3  src/bos/usr/sbin/uprintfd/Makefile, cmdoper, bos411, 9428A410j 3/17/93 16:34:02
#
# COMPONENT_NAME: CMDOPER
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993.
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= uprintfd

ILIST		= uprintfd
IDIR		= /usr/sbin/


.include <${RULES_MK}>
