# @(#)56	1.2  src/rspc/kernext/pm/pmmd/Makefile, pwrsysx, rspc41J, 9513A_all 3/28/95 14:47:08
#
# COMPONENT_NAME: PWRSYSX
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= 6030 IBM8301

.include <${RULES_MK}>
