# @(#)47        1.2  src/bos/usr/sbin/halt/Makefile, cmdoper, bos411, 9428A410j 3/3/93 15:56:30
#
# COMPONENT_NAME: CMDOPER
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993.
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= halt
MSGHDRS		= halt_msg.h
CATFILES	= halt.cat
HFILES		= ${MSGHDRS}

ILIST		= halt
IDIR		= /usr/sbin/


.include <${RULES_MK}>
