# @(#)45        1.1  src/bos/usr/sbin/renice/Makefile, cmdcntl, bos411, 9428A410j 8/5/92 17:24:29
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= renice
MSGHDRS		= renice_msg.h
CATFILES	= renice.cat
HFILES		= ${MSGHDRS}

ILIST		= renice
IDIR		= /usr/sbin/


.include <${RULES_MK}>
