# @(#)26        1.2  src/bos/usr/sbin/install/messages/Makefile, cmdinstl, bos411, 9428A410j 3/25/94 15:26:17
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


MSGHDRS		= cmdinstl_e_msg.h
CATFILES	= cmdinstl_e.cat
HFILES		= ${MSGHDRS}

INCLUDES	= cmdinstl_e_msg.h 

ILIST		= 
IDIR		= /usr/include/


.include <${RULES_MK}>

