$ @(#)29	1.1  src/tenplus/e2/common/poundfile.msg, tenplus, tenplus411, GOLD410 3/17/93 13:58:41
$
$ COMPONENT_NAME: (INED) INed Editor
$ 
$ ORIGINS:  27
$ 
$ This module contains IBM CONFIDENTIAL code. -- (IBM
$ Confidential Restricted when combined with the aggregated
$ modules for this product)                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1991
$ All Rights Reserved
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$quote "
$
$set MS_POUNDFILE 
$
$ Translator:  do not translate anthing that looks like %s or %d or
$ %1$s or %2$d etc.
$
M_USAGE "0611-276 Usage: poundfile StackFile TextFile"
$ Do not translate "poundfile"
$
M_STACK "0611-277 poundfile: Cannot open stack file %s.\n\
\tCheck path name and permissions."
$ Do not translate "poundfile"
$
M_TEXT "0611-278 poundfile: Cannot open text file %s.\n\
\tCheck path name and permissions."
$ Do not translate "poundfile"
