# @(#)80	1.4  src/rspc/kernext/disp/Makefile, rspcdisp, rspc411, 9436D411b 9/7/94 11:41:31
# COMPONENT_NAME:  RSPCDISP
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS  = pcifga pcihga pciwfg pcigga pciiga

SUBDIRS		= pcifga pcihga pciwfg pcigga pciiga

.include <${RULES_MK}>
