# @(#)81	1.5  src/tcpip/usr/include/isode/Makefile, tcpip, tcpip411, GOLD410 2/18/94 11:39:55
#
# 
# COMPONENT_NAME: SNMP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS			= pepy pepsy snmp

EXPINC_SUBDIRS		= ${SUBDIRS}

DATAFILES 		=  acpkt.h acsap.h cmd_srch.h config.h dgram.h \
			ftam.h general.h internet.h isoaddrs.h \
			isoservent.h logger.h manifest.h mpkt.h pepdefs.h \
			pepsy.h ppkt.h psap.h psap2.h ronot.h ropkt.h \
			rosap.h rosy.h rtpkt.h rtsap.h spkt.h ssap.h \
			sys.dirent.h tailor.h tp4.h tpkt.h tsap.h \
			usr.dirent.h x25.h 

INCLUDES		= ${DATAFILES}

ILIST			= ${INCLUDES}
IDIR			= /usr/include/isode/
IMODE			= 644

.include <${RULES_MK}>
