# @(#)20    1.5  src/rspc/kernext/inc/Makefile, rspccfg, rspc41J, 9511A_all  3/14/95  09:26:35
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1993, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

INCLUDES	= pci.h pcmciass.h pcmciacs.h pcmciacsAix.h

EXPDIR		= /kernel/include/sys/

.include <${RULES_MK}>
