#!/etc/drivers/ataide
* @(#)03        1.3  src/rspc/kernext/isa/ide/ataide.exp, isaide, rspc41J, 9510A 2/21/95 09:22:04
*
* COMPONENT_NAME: (ISAIDE) IBM ATA/IDE Adap. Driver Top Half Export List
*
* FUNCTIONS:
*
* ORIGINS: 27
*
* (C) COPYRIGHT International Business Machines Corp. 1995
* All Rights Reserved
* Licensed Materials - Property of IBM
*
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
