# @(#)27        1.1  src/rspc/kernext/isa/ide/devices.isa_sio.PNP0600.rte.trc.S, isaide, rspc41J 3/13/95 09:54:29
#
#   COMPONENT_NAME: ISAIDE
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt
+2A0 1.0 "IDEDD" \
        $DD1
