# @(#)77	1.3  src/tcpip/usr/ccs/lib/libsmit/Makefile, tcpip, tcpip411, GOLD410 2/15/93 14:40:39
# COMPONENT_NAME: TCPIP - SMIT Utility library
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES		= libsmit.a

EXPLIB_TARGETS		= export_libsmit.a

ILIST                   = libsmit.a
IDIR                    = /usr/ccs/lib/
IMODE                   = 644

OFILES			= libsmit.o

.include <${RULES_MK}>
