# @(#)24	1.1  src/tw/usr/Makefile, tw, tw411, GOLD410 12/8/92 15:42:06
#
# COMPONENT_NAME: TW
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS			= lpp

.include <${RULES_MK}>
