# 
# 
#
# ORIGINS: 27 
#
#
# 
.include	<${MAKETOP}nfs/NFS.mk>

VPATH		= ${MAKETOP}/nfs/usr/include/rpcsvc

DATAFILES	= \
	klm_prot.h \
	mount.h

INCLUDES	= \
	${DATAFILES}
	
IDIR		= /kernel/include/rpcsvc/

.include <${RULES_MK}>
