# @(#)15    1.9  src/rspc/usr/Makefile, rspccfg, rspc41J, 173270.rspc  3/9/95  16:35:08
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= include

EXPLIB_SUBDIRS		= lib ccs

SUBDIRS			= include ccs lib lbin sbin bin

.include <${RULES_MK}>

