# 
#
# ORIGINS: 27 
#
#
# 

EXPINC_SUBDIRS		= yp

SUBDIRS		= automount \
	keyserv		\
	netdisk		\
	rexd		\
	rpc.bootparamd	\
	rpc.lockd	\
	rpc.pcnfsd	\
	rpc.statd	\
	sysmgt		\
	yp

ILIST	= \
	biod		\
	exportfs	\
	gfsinstall	\
	nfsd		\
	nfso		\
	nfsstat		\
	portmap		\
	rpc.rstatd	\
	rpc.mountd	\
	rwall		\
	spray

IDIR		= /usr/sbin/

.include <${RULES_MK}>
