$ @(#)51        1.1  src/tcpip/usr/sbin/ip_auditpr/ip_auditpr.msg, tcpras, tcpip411, GOLD410 3/6/90 16:40:11
$
$ COMPONENT_NAME: (TCPIP) tcp/ip communication protocol support
$
$ FUNCTIONS:  ip_auditpr.msg
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$ scmc msg file created Tue Mar  6 09:09:27 1990
$ user:  kent

$quote "

$len 
$set MS_ip_auditpr        Define initial set#

M_MSG_1              "usage: %s [-i <spaces>] -e audit_event\n"
M_MSG_2              "Non-supported TCP/IP kernel event name!\n"
M_MSG_4              "Unknown TCP/IP audit event!\n"
M_MSG_13             "Unknown kernel socket operation!\n"
M_MSG_20             "Unknown kernel socket operation!\n"
M_MSG_21             "Unknown kernel protocol domain!\n"
M_MSG_22             "No path name"
M_MSG_24             "No IP address available"
M_MSG_30             "Unknown kernel TCP/IP ioctl!\n"
M_MSG_46             "Unknown kernel TCP/IP ioctl!\n"
M_MSG_49             "UP "
M_MSG_50             "DOWN "
M_MSG_51             "HOST ROUTE"
M_MSG_52             "NET ROUTE"
M_MSG_62             "Unknown kernel socket type!\n"
M_MSG_64             "Unknown kernel socket type!\n"
M_MSG_65             "Unknown kernel protocol domain!\n"
M_MSG_71             "Unknown kernel protocol domain!\n"
M_MSG_75             "Unknown kernel socket type!\n"
M_MSG_79             "Unknown kernel socket protocol!\n"
