# @(#)21        1.2  src/bos/usr/sbin/install/inurecv/Makefile, cmdinstl, bos411, 9428A410j 11/7/92 14:08:47
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= inurecv
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= inurecv
IDIR		= /usr/sbin/

INCFLAGS	= -I../messages -I../include

LIBS		= -linulib -lodm -lswvpd -ls -lcfg

.include <${RULES_MK}>
