# @(#)61	1.7  src/tenplus/hlib/DT/Makefile, tenplus, tenplus411, GOLD410 6/8/93 13:48:15
#
# COMPONENT_NAME: (INED) INed Editor
# 
# ORIGINS:  9, 10, 27
# 
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
# 
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

OFILES =  DTinit.o DTlength.o DTlookup.o
LIBRARIES = libDT.a 
INCFLAGS = -I${MAKETOP}/tenplus/include

.include <${RULES_MK}>
