# @(#)47  1.2 src/rspc/kernext/pci/kent/devices.pci.22100020.rte.trc.S, pcient, rspc41J, 9507B  1/25/95  12:32:02
#
#   COMPONENT_NAME: PCIENT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt
+2A4 1.0 "@kentdd" \
        "PCI ENT DD XMT: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4 

+2A5 1.0 "@kentdd" \
        "PCI ENT DD RCV: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+2A6 1.0 "@kentdd" \
        "PCI ENT DD GEN: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4
