# @(#)78        1.5  src/rspc/usr/include/sys/Makefile, Makefiles, rspc41J, 9511A_all 3/14/95 09:26:38
#
#   COMPONENT_NAME: MAKEFILES
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993, 1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH           = ${MAKETOP}/rspc/kernext/inc

INCLUDES        = pci.h pcmciass.h pcmciacs.h pcmciacsAix.h

EXPDIR          = /usr/include/sys/

ILIST           = pcmciacs.h pcmciass.h pcmciacsAix.h
IDIR            = /usr/include/sys/

.include <${RULES_MK}>
