# @(#)43	1.1  src/tcpip/usr/sbin/chservices/Makefile, tcpinet, tcpip411, GOLD410 3/19/93 10:25:03
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 27 
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS			= chservices
MSGHDRS			= chservices_msg.h
CATFILES		= chservices.cat

ILIST                   = chservices
IDIR                    = /usr/sbin/

.include <${RULES_MK}>
