# @(#)51        1.1  src/bos/usr/samples/cfg/Makefile, cfgsamp, bos411, 9428A410j 8/19/93 16:48:05
# COMPONENT_NAME: CFGSAMP
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES               = cfgxxx.c cfgyyy.c cfgzzz.c chgyyy.c defxxx.c \
   defyyy.c defzzz.c startzzz.c ucfgxxx.c ucfgyyy.c \
   udefxxx.c udefyyy.c xxx.add yyy.add zzz.add

ILIST                   = ${DATAFILES}
IDIR                    = /usr/samples/cfg/

.include <${RULES_MK}>
