#
#
# ORIGINS: 27 
#
#
.include	<${MAKETOP}nfs/NFS.mk>

MSGHDRS		= cmdnfs_msg.h
CATFILES	= cmdnfs.cat
HFILES		= ${MSGHDRS}

INCLUDES	= ${HFILES}

${MSGHDRS}_IDIR	= /usr/include/

.include <${RULES_MK}>
