# @(#)76	1.3  src/tcpip/usr/ccs/lib/libffdb/Makefile, tcpip, tcpip411, GOLD410 2/15/93 14:37:27
# COMPONENT_NAME: TCPIP - Flat File Database Utility library
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES		= libffdb.a
MSGHDRS                 = libffdb_msg.h
CATFILES                = libffdb.cat
HFILES                  = ${MSGHDRS}

EXPLIB_TARGETS		= export_libffdb.a

ILIST                   = libffdb.a
IDIR                    = /usr/ccs/lib/
IMODE                   = 644

OFILES			= libffdb.o

.include <${RULES_MK}>
