# @(#)26	1.2  src/tcpip/usr/lib/Makefile, tcpip, tcpip411, GOLD410 11/9/93 08:33:02
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= libsnmp

EXPLIB_SUBDIRS	= libisode libsnmp

SUBDIRS		= \
	${EXPLIB_SUBDIRS}

.include <${RULES_MK}>

