# @(#)67	1.2  src/tcpip/usr/ccs/Makefile, tcpip, tcpip411, GOLD410 12/8/92 13:08:42
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= lib

EXPLIB_SUBDIRS		= lib

SUBDIRS			= lib

.include <${RULES_MK}>
