# @(#)01        1.1  src/bos/usr/sbin/chroot/Makefile, cmdfiles, bos411, 9428A410j 8/5/92 17:52:59
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= chroot
MSGHDRS		= chroot_msg.h
CATFILES	= chroot.cat
HFILES		= ${MSGHDRS}

ILIST		= chroot
IDIR		= /usr/sbin/


.include <${RULES_MK}>
