# @(#)87	1.1  src/rspc/usr/lib/boot/softros/Makefile, rspc_softros, rspc411, GOLD410 4/18/94 15:25:20
#
#   COMPONENT_NAME: RSPC_SOFTROS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS 	= lib roslib 

SUBDIRS		=  lib roslib aixmon

.include	<${RULES_MK}>
