# @(#)57        1.2  src/bos/usr/sbin/grpck/Makefile, cmdsadm, bos411, 9428A410j 3/25/94 14:49:00
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= grpck
MSGHDRS		= grpck_msg.h
CATFILES	= grpck.cat
HFILES		= ${MSGHDRS}

ILIST		= grpck
IDIR		= /usr/sbin/

OFILES		= grpck.o comfix.o

LIBS		= -ls

.include <${RULES_MK}>
