# @(#)31	1.1  src/tcpip/usr/samples/snmpd/dpi/ping_eng/makefile, snmp, tcpip411, GOLD410 9/13/93 15:08:59
# COMPONENT_NAME: (SNMP) Simple Network Management Protocol Daemon
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991, 1993
# All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Licensed Material - Property of IBM
#
#
.include <${MAKETOP}tcpip/usr/Make.cfg>

VPATH			= ${TARGET_MACHINE}
DATAFILES		= Makefile init.h sqeping.c subagent.c README \
			  io_lib.c ping_eng.c stats.c init.c io_lib.h \
			  ping_eng.my stats.h

ILIST			= ${DATAFILES}
IDIR			= /usr/samples/snmpd/dpi/ping_eng/
IMODE			= 644

.include <${RULES_MK}>
