# @(#)02	1.2  src/msg/bos/No_NO/Makefile, bosmsg, msg411, GOLD410 2/9/94 15:03:45
#
# COMPONENT_NAME: bosmsg
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential	Restricted when
# combined with	the aggregated modules for this	product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT	International Business Machines	Corp. 1994
# All Rights Reserved
#
# US Government	Users Restricted Rights	- Use, duplication or
# disclosure restricted	by GSA ADP Schedule Contract with IBM Corp.
#

MSGLANG	= No_NO
SOURCE_CODESET = ISO8859-1
TARGET_CODESET = IBM-850

VPATH	= ${MAKETOP}/msg/bos/no_NO:${MAKETOP}/msg/bos/base

.include <${MAKETOP}/msg/bos/bosmsg.mk>
