$ @(#)62        1.5.2.2  src/bos/usr/sbin/link/link.msg, cmdfiles, bos411, 9428A410j 9/1/93 16:48:13
$
$ COMPONENT_NAME: (CMDFILES) commands that deal with the file system
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$ $ Message numbers 293 - 299 reserved for this file.
$
$set MS_LINK
$
$ Do not translate link or unlink -- these are the command names.

LINK_USAGE      "Usage: link FromFile ToFile\n"
UNLINK_USAGE    "Usage: unlink File\n"
OOPS            "(un)link: 0653-293 Command name should be link or unlink; using link\n"
INSUF_PRIV	"%s: 0653-294 Insufficient priviledges\n"

