# @(#)02        1.1  src/bos/usr/sbin/link/Makefile, cmdfiles, bos411, 9428A410j 8/5/92 17:53:07
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= link
MSGHDRS		= link_msg.h
CATFILES	= link.cat
HFILES		= ${MSGHDRS}

ILIST		= link
IDIR		= /usr/sbin/


.include <${RULES_MK}>
