# @(#)06        1.1  src/bos/usr/sbin/flcopy/Makefile, cmdarch, bos411, 9428A410j 9/13/92 18:07:52
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS        = flcopy
MSGHDRS         = flcopy_msg.h
CATFILES        = flcopy.cat
HFILES          = ${MSGHDRS}

ILIST           = flcopy
IDIR            = /usr/sbin/


.include <${RULES_MK}>
