# @(#)79        1.1  src/bos/usr/sbin/route/Makefile, cmdnet, bos411, 9428A410j 8/5/92 17:47:37
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= route
MSGHDRS		= route_msg.h
CATFILES	= route.cat
HFILES		= ${MSGHDRS}

ILIST		= route
IDIR		= /usr/sbin/

CFLAGS		= -DS5 -D_BSD=44 -DSLIPDISC=2

.include <${RULES_MK}>
