# @(#)32        1.1  src/bos/usr/sbin/lsps/Makefile, cmdps, bos411, 9428A410j 8/31/92 19:17:42
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= lsps
MSGHDRS		= cmdps_msg.h
CATFILES	= cmdps.cat
HFILES		= ${MSGHDRS}

ILIST		= lsps
IDIR		= /usr/sbin/

LIBS		= -lodm -lcfg

.include <${RULES_MK}>
