# @(#)37        1.2  src/bos/usr/sbin/acct/ac/Makefile, cmdacct, bos411, 9428A410j 2/2/93 16:46:59
# COMPONENT_NAME: CMDACCT
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= ac
MSGHDRS		= ac_msg.h
CATFILES	= ac.cat
HFILES		= ${MSGHDRS}

ILIST		= ac
IDIR		= /usr/sbin/acct/

LIBS		= -lbsd

.include <${RULES_MK}>
