# @(#)44       1.2  src/bos/usr/lpp/perfagent/lockstat/Makefile, lockstat, perf412, 9446C 11/18/94 10:32:26 

# COMPONENT_NAME: LOCKSTAT
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

#
# LEVEL 1,  5 Years Bull Confidential Information
#

ILIST	= lockname.db
IDIR	= /usr/lpp/perfagent/lockstat/

.include <${RULES_MK}>

