# @(#)31        1.2  src/bos/usr/sbin/cfgmgr/Makefile, cfgmethods, bos411, 9428A410j 6/25/93 09:48:27
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${TARGET_MACHINE}

PROGRAMS	= cfgmgr
MSGHDRS		=
CATFILES	= cfgmgr.cat
OTHERS		= ${CATFILES}

ILIST		= cfgmgr
IDIR		= /usr/sbin/

OFILES		= cfgmgr.o

LIBS		= -ls -lodm -lcfg

.include <${RULES_MK}>
