# @(#)64        1.1  src/bos/usr/samples/fd/Makefile, fdsamp, bos411, 9428A410j 10/12/93 14:32:17

#
# COMPONENT_NAME: FDSAMP
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



ILIST		= fd.c fd_bot.c fd_local.h
IDIR		= /usr/samples/fd/

.include <${RULES_MK}>
