# @(#)38	1.2  src/bos/usr/lpp/tls/dict/Makefile, libtw, bos411, 9428A410j 9/20/93 08:35:37
#
# COMPONENT_NAME:  LIBTW
#
# FUNCTIONS: Taiwan Input Method Dictionary Files
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST 	= phsysdict tjsysdict
IDIR	= /usr/lpp/tls/dict/

.include <${RULES_MK}>
