# @(#)44	1.3  src/tcpip/usr/lpp/Makefile, tcpip, tcpip411, GOLD410 9/9/93 17:19:00
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 10  26  27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1993
# All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Licensed Materials - Property of IBM
#

VPATH			= ${TARGET_MACHINE}
SUBDIRS                 = tcpip

.include <${RULES_MK}>
