# @(#)87	1.1  src/bos/usr/samples/fp/Makefile, fpsamp, bos411, 9428A410j 9/8/93 10:45:22
#
# COMPONENT_NAME: fpsamp
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= sigfpe_samp1.c sigfpe_samp2.c sigfpe_samp3.f 
IDIR		= /usr/samples/fp/

.include <${RULES_MK}>
