#!/etc/drivers/idecdrom
* @(#)63        1.3  src/rspc/kernext/idecdrom/idecdrom.exp, idecd, rspc41J, 9510A 2/21/95 09:03:36
*
* COMPONENT_NAME: (IDECD) IDE CD-ROM Device Driver Top Half Export List
*
* FUNCTIONS:
*
* ORIGINS: 27
*
* (C) COPYRIGHT International Business Machines Corp. 1995
* All Rights Reserved
* Licensed Materials - Property of IBM
*
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
