# @(#)68        1.6  src/tcpip/usr/ccs/lib/Makefile, tcpip, tcpip411, 9433B411a 8/17/94 09:30:22
#
# COMPONENT_NAME: tcpip
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS	= libtcp_ocs libtcp_audit libffdb libsmit libinetodm \
		  libbsdutil

SUBDIRS		= \
	${EXPLIB_SUBDIRS}

.include <${RULES_MK}>

