# @(#)77	1.1  src/rspc/kernext/disp/pciiga/inc/Makefile, pciiga, rspc411, 9436D411b 9/5/94 16:31:53
#
#   COMPONENT_NAME: pciiga
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

EXPDIR          = /kernel/include/graphics/

INCLUDES        = igadds.h iga_reg.h iga_regval.h \
                  iga.h igaddf.h igaldat.h

.include <${RULES_MK}>


