$ @(#)30	1.1  src/tcpip/usr/sbin/compat/notinet.msg, tcpip, tcpip411, GOLD410 3/30/94 17:28:42
$
$   COMPONENT_NAME: tcpip
$
$   FUNCTIONS: none
$
$   ORIGINS: 27
$
$
$   (C) COPYRIGHT International Business Machines Corp. 1994
$   All Rights Reserved
$   Licensed Materials - Property of IBM
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ messages for notinet  
$
$ The range of message numbers assigned to this file are 181-186 
$quote "         define quote character.
$len 
$set MS_NOTINET        Define initial set#

$ Do not translate notinet:, %s 
ERR_FTOK             "%s: 0822-181 The shared memory system call ftok failed.\n"
$ Do not translate ftok 
$ share memory failure on ftok 
