# @(#)31  1.1  src/bos/usr/sbin/nddstat/tokstat/Makefile, nddstat, bos411, 9428A410j 2/23/94 18:17:38 
#
#   COMPONENT_NAME: NDDSTAT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1989,1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
VPATH		= ../common

PROGRAMS	= tokstat
MSGHDRS         = tokstat_msg.h
CATFILES        = tokstat.cat
HFILES          = ${MSGHDRS}

ILIST		= tokstat
IDIR		= /usr/sbin/

OFILES		= main.o tokstat.o

.include <${RULES_MK}>
