# @(#)91	1.5  src/tcpip/usr/samples/snmpd/smux/makefile, snmp, tcpip411, GOLD410 9/13/93 15:17:29
#
# COMPONENT_NAME: (SNMP) Simple Network Management Protocol Daemon
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991, 1993
# All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Licensed Material - Property of IBM
#
#

.include <${MAKETOP}tcpip/usr/Make.cfg>

VPATH			= ${TARGET_MACHINE}
SUBDIRS			= sampled
DATAFILES		= Makefile README smux.txt unixd.c unixd.defs \
			   isodetailor

ILIST			= ${DATAFILES}
IDIR			= /usr/samples/snmpd/smux/
IMODE			= 644

.include <${RULES_MK}>
