$ @(#)52  1.2.1.6  src/bos/usr/sbin/bootinfo/bootinfo.msg, bosboot, bos411, 9428A410j 4/29/94 16:22:37
$
$ COMPONENT_NAME: (BOSBOOT) Base Operating System Boot
$
$ FUNCTIONS:  bootinfo.msg
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1994
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "

$set 250

1 "\nusage: bootinfo [ -P psize -s disk ] |-b |-B disk |-c |\n"
2 "\t\t-k |-m |-q adapter |-r |-t |-T |-o disk |-z\n"
$ Do not translate bootinfo
$ Deleted messages 3 - 20
21 "\n 0301-268 Object Data Manager initialize failed!\n"
$ Object Data Manager (ODM) is an AIX specific facility intended
$  for storing system information.
$ Deleted message 22
$ End of bootinfo.msg
