# @(#)27        1.14  src/bos/usr/sbin/install/scripts/Makefile, cmdinstl, bos411, 9440A411d 10/5/94 07:46:14
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS        = 
SCRIPTS		= instal cleanup inudocm rminstal deinstal inubosboot inurid  \
		  migrate_cfg sm_inst.awk sm_inst automsg
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}
OTHERS		= ${SCRIPTS}

ILIST		= instal cleanup inudocm rminstal deinstal inubosboot inurid  \
		  migrate_cfg sm_inst.awk sm_inst automsg

IDIR		= /usr/lib/instl/

inudocm_IDIR	= /usr/sbin/

INCFLAGS        = -I../messages -I../include

OFILES          = 

LIBS            = 

.include <${RULES_MK}>
