# @(#)11	1.4  src/rspc/usr/lib/boot/softros/lib/libstand/Makefile, rspc_softros, rspc41J, 9515A_all 4/11/95 15:06:06
#
#   COMPONENT_NAME: RSPC_SOFTROS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES       = libsrstand.a
EXPLIB_TARGETS  = export_libsrstand.a
IDIR            = /usr/lib/masters/

OFILES          = asmutil.o am_con.o device.o exec.o util.o

CFLAGS          = -qcpluscmt -qarch=ppc

INCFLAGS        = -I${MAKETOP}/rspc/usr/lib/boot/softros/include

.include <${RULES_MK}>
