# @(#)97        1.1  src/bos/usr/sbin/fuser/Makefile, cmdfs, bos411, 9428A410j 8/5/92 17:52:27
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= fuser
MSGHDRS		= fuser_msg.h
CATFILES	= fuser.cat
HFILES		= ${MSGHDRS}

ILIST		= fuser
IDIR		= /usr/sbin/


.include <${RULES_MK}>
