# @(#)80	1.2  src/tcpip/usr/include/isode/snmp/Makefile, tcpip, tcpip411, GOLD410 1/21/93 10:51:36
# 
# COMPONENT_NAME: SNMP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES		= ibmsmux.h io.h logging.h objects.h smux.h

INCLUDES		= ${DATAFILES}

ILIST			= ${INCLUDES}
IDIR			= /usr/include/isode/snmp/
IMODE			= 644

.include <${RULES_MK}>
