# @(#)69        1.1  src/bos/usr/sbin/sa/Makefile, cmdstat, bos411, 9428A410j 8/5/92 17:43:04
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= sa
SCRIPTS		= sa1 sa2
MSGHDRS		= sa_msg.h
CATFILES	= sa.cat
HFILES		= ${MSGHDRS}

ILIST		= sa sa1 sa2
IDIR		= /usr/sbin/
sa1_IDIR	= /usr/lib/sa/
sa2_IDIR	= /usr/lib/sa/

INCLUDES	= sa.h
sa.h_IDIR	= /usr/include/

.include <${RULES_MK}>
