# @(#)65        1.1  src/rspc/usr/lib/boot/disable_hibernation/Makefile, pwrcmd, rspc41J, 9517B_all 4/9/95 23:03:56
#
# COMPONENT_NAME: (PWRCMD) Power Management Commands
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= disable_hibernation

ILIST		= disable_hibernation
IDIR		= /usr/lib/boot/

.include <${RULES_MK}>
