# @(#)60	1.1  src/rspc/etc/Makefile, Makefiles, rspc41J, 9509A_all 2/20/95 10:49:14
#
#   COMPONENT_NAME: Makefiles
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= acfgd

.include <${RULES_MK}>
