# @(#)15        1.9  src/bos/usr/sbin/install/Makefile, cmdinstl, bos411, 9428A410j 4/22/94 13:12:39
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= messages
EXPLIB_SUBDIRS	= inulib ckprereq

SUBDIRS		= bffcreate ckprereq client installp instfix inucp \
		  inurdsd inurecv inurest inusave inutoc inuumsg \
		  inu_tape_dd messages scripts netls sysck migrate merge

.include <${RULES_MK}>
