$ @(#)49        1.4 4/25/91 19:28:52
$
$ COMPONENT_NAME: CMDSCCS       source code control system
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$
$quote /
$set 1
1 /Command usage error.\n\
\tSpecify only two files on the command line.\n/
$set 2
1 /Do not substitute standard input (-) for both files on the command line.\n\
\tChoose one file or the other to designate as standard input.\n/
$set 4
1 /The third parameter must be numeric.\n\
\tIf you choose to specify a line segment on the command line, the third\n\
\tparameter must be numeric.\n/
$set 6
1 /The specified program failed.\n\
\tThe named program terminated with an error.\n\
\tFollow local problem reporting procedures.\n/
