$ @(#)56        1.4 4/25/91 19:29:12
$
$ COMPONENT_NAME: CMDSCCS       source code control system
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "
$set 49
1 "Usage: get [-cCutoff] [-iList] [-rSID] [-wString] [-xList] [-gmnpst]\n\
\t[-l[p]] File ...\n\
\tor\n\
\tget {-e|-k} [-cCutoff] [-iList] [-rSID] [-wString] [-xList] [-bst]\n\
\t[-l[p]] File ...\n\
\tCreates a specified version of a Source Code Control System (SCCS) file.\n"
