$ @(#)60        1.4 4/25/91 19:29:24
$
$ COMPONENT_NAME: CMDSCCS       source code control system
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote #
$set 1
1 #The specified parameter is not valid.\n\
Specify a valid command or error code.\n\
No information associated with your request is available.\n\
You must specify an existing command or error code for the help command.\n#
$set 2
1 #Command parameter cannot exceed 49 characters.\n\
No command parameter can be more than 49 characters long on the sccshelp\n\
command line.\n#
