# @(#)63        1.2  src/bos/usr/share/lib/sccshelp/Makefile, cmdsccs, bos411, 9434A411a 8/18/94 11:13:59
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

CATFILES	= h.ad.cat h.admin.cat h.bd.cat h.bdiff.cat h.cb.cat \
		  h.cdc.cat h.cm.cat h.co.cat h.comb.cat h.de.cat \
		  h.default.cat h.delta.cat h.ge.cat h.get.cat h.he.cat \
		  h.help.cat h.prs.cat h.prskwd.cat h.rc.cat h.rmdel.cat \
		  h.sccsdf.cat h.un.cat h.ut.cat h.val.cat h.vc.cat \
		  h.what.cat

DATAFILES	= ad bd cb cm cmds co de default ge he prs rc un ut vc

ILIST		= ${DATAFILES}
IDIR		= /usr/share/lib/sccshelp/

OTHERS	= $(CATFILES)

.include <${RULES_MK}>
