# @(#)83  1.1  src/rspc/kernext/disp/pcigga/inc/Makefile, pcigga, rspc411, 9435D411a 9/2/94 15:59:14
#
#   COMPONENT_NAME: pcigga
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPDIR          = /kernel/include/graphics/

INCLUDES        = ggadds.h gga_reg.h gga_regval.h \
		gga.h ggaddf.h ggaldat.h 

.include <${RULES_MK}>


