# 
# 
#
# ORIGINS: 27 
#
#
# 

DATAFILES	= \
	export.h \
	nfs.h \
	nfs_clnt.h \
	nfs_load.h \
	nfs_trc.h \
	rnode.h \
	nfs_fscntl.h

INCLUDES	= \
	${DATAFILES} \
	nfs_swap.h \
	sunglue.h \
	dnlc.h \
	netpriv.h \
	pacl.h
	
	
IDIR		= /usr/include/nfs/

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
