# @(#)40	1.1  src/tcpip/usr/lbin/Makefile, tcpip, tcpip411, GOLD410 12/8/92 11:46:25
# 
# COMPONENT_NAME: TCPIP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 10  26  27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH			= ${TARGET_MACHINE}
SUBDIRS                 = fingerd ftpd rexecd rlogind rshd talkd \
			telnetd tftpd

.include <${RULES_MK}>
