$ @(#)52	1.2  src/bos/usr/sbin/strerr/strerr.msg, cmdpse, bos411, 9428A410j 5/20/91 18:17:13
$
$ COMPONENT_NAME: (CMDPSE) STREAMS commands
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ Messages for strerr.
$ Do not translate strerr.
$ Message numbers have been assigned a range of XXX - YYY
$
$quote "		define quote character.
$set MS_STRERR		Define initial set#

MSG1	"strerr: couldn't open log device"
MSG2	"strerr: already registered\n"
