# @(#)82	1.2  src/tcpip/usr/include/isode/pepy/Makefile, tcpip, tcpip411, GOLD410 7/7/94 16:31:27
# 
# COMPONENT_NAME: SNMP Makefile
# 
# FUNCTIONS: 
#
# ORIGINS: 27 
#
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

INCLUDES		= UNIV-types.h

ILIST			= ${INCLUDES}
IDIR			= /usr/include/isode/pepy/
IMODE			= 644

.include <${RULES_MK}>
