# @(#)62        1.1  src/bos/usr/sbin/mkram/Makefile, Makefiles, bos411, 9428A410j 8/5/92 18:02:47
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH 		=${MAKETOP}/bos/kernel/io

PROGRAMS	= mkram

OFILES		= mkram.o rampack.o

ILIST		= mkram
IDIR		= /usr/sbin/

.include <${RULES_MK}>
