# @(#)81	1.3  src/bos/usr/sbin/netstart/Makefile, cmdnet, bos411, 9428A410j 4/19/94 09:14:47
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= rc.net rc.net.serial rc.bsdnet hosts
IDIR		= /etc/
NOUPDATE_LIST	= /etc/rc.net /etc/rc.net.serial /etc/rc.bsdnet /etc/hosts



.include <${RULES_MK}>
