# @(#)68        1.1  src/bos/usr/sbin/chtcb/Makefile, cmdspriv, bos411, 9428A410j 8/5/92 17:42:37
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= chtcb
MSGHDRS		= chtcb_msg.h
CATFILES	= chtcb.cat
HFILES		= ${MSGHDRS}

ILIST		= chtcb
IDIR		= /usr/sbin/

LIBS		= -ls

.include <${RULES_MK}>
