# @(#)36	1.1  src/bos/usr/lpp/tls/defaults/Makefile, libtw, bos411, 9428A410j 1/13/93 12:35:38
# COMPONENT_NAME:  LIBTW
#
# FUNCTIONS: Taiwan Input Method Defaults File
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST 	= timrc
IDIR	= /usr/lpp/tls/defaults/

.include <${RULES_MK}>
