# @(#)72	1.3  src/tcpip/usr/ccs/lib/libtcp_audit/Makefile, tcpip, tcpip411, GOLD410 2/15/93 14:42:08
# COMPONENT_NAME: TCPIP - Audit Utility library
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES		= libtcp_audit.a

EXPLIB_TARGETS		= export_libtcp_audit.a

ILIST			= libtcp_audit.a
IDIR			= /usr/ccs/lib/
IMODE			= 644

CFLAGS			= -D_CSECURITY -D_BSD=44
OFILES			= netrc.o tcpip_audit.o

.include <${RULES_MK}>
