# @(#)81	1.2  src/rspc/kernext/pm/Makefile, pwrsysx, rspc41J, 9510A 3/8/95 06:49:30
#
# COMPONENT_NAME: PWRSYSX
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= pmmi pmmd wakeup

.include <${RULES_MK}>
