# @(#)90        1.1  src/bos/usr/sbin/feprom_update/Makefile, cmdcntl, bos411, 9428A410j 12/15/93 07:36:01

# COMPONENT_NAME: (CMDCNTL)
#
# FUNCTIONS:
#
# ORIGINS: 83
#
# LEVEL 1,5 Years Bull Confidential Information
#

PROGRAMS	= feprom_update
MSGHDRS		= feprom_update_msg.h
CATFILES	= feprom_update.cat
HFILES		= ${MSGHDRS}

ILIST		= feprom_update
IDIR		= /usr/sbin/


.include <${RULES_MK}>
