# @(#)64	1.58  src/bos/usr/sbin/Makefile, Makefiles, bos412, 9445C412b 11/2/94 03:37:08
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1988,1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= install sa fsck mkdev acct

EXPLIB_SUBDIRS		= lvm install

SUBDIRS		= \
	XNSrouted	acct adfutil	arp assist audit	auditbin \
	auditcat	auditconv	auditpr	auditselect	auditstream \
	autopush	backbyname	backup	bindprocessor	bootexpand \
	bootinfo	bootpd	bootrec	bosboot	catman	cfgmgr	chcons \
	chdev	chroot	chtcb	comsat	cpu_state	cron	crash \
	defragfs	devinstall devnm	dfsck   diskusg dtappintegrate \
	dumpfs	execerror	fbcheck	feprom_update	ff \
	flcopy	format	fsck	fsdb	fuser	grpck	halt	hostid \
	ifconfig	init	install	keycfg killall	link	logform	logredo \
	lsattr	lsconn	lscons	lsdev	lsfs	lsgroup	lsjfs	lsnim \
	lsparent        lsps    lsresource      lsuser  lsvfs   lvm     machstat \
	mkboot	mkdev	mkfs	mkinsttape	mkitab	mklost+found \
	mknod	mkpasswd	mkproto	mkram	monitord	mount \
	mpcfg	mvdir	ncheck \
	ndb	nddstat	netstart	netstat	nim	nimclient \
	nimesis nimconfig \
	niminit	no	open_door	penable	perf	ping	probe	proto	pse	quota \
	rdump	reboot	renice	restbyname	restore	rmdev \
	rmgroup rmt	rmuser	route	rrestore	sa	sar \
	savebase	savecore	shutdown	skulker \
	slattach	slibclean	sliplogin	snap	strace	strchg \
	strclean	strconf	strerr	strinfo	strload	survd	swapon \
	swcons	sync	syncd	syslogd	tapechk	trace	trpt	tsm \
	update	uprintfd	wall	watch

.include <${RULES_MK}>
