# @(#)81        1.3  src/bos/usr/share/lib/pub/sets/Makefile, cmdsets, bos411, 9428A410j 1/22/93 17:08:40
# COMPONENT_NAME: cmdsets
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= ascii ebcdic greek tabs
IDIR		= /usr/share/lib/pub/

.include <${RULES_MK}>
