# @(#)51  1.1  src/bos/usr/sbin/nddstat/common/Makefile, nddstat, bos411, 9428A410j 2/10/94 13:59:30 
#
#   COMPONENT_NAME: NDDSTAT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1989,1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

MSGHDRS		= nddstat_msg.h
CATFILES	= nddstat.cat
OTHERS		= ${MSGHDRS}

.include <${RULES_MK}>
