# @(#)40        1.2  src/bos/usr/sbin/comsat/Makefile, cmdmailx, bos411, 9428A410j 1/21/93 18:01:21
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= comsat
MSGHDRS		= comsat_msg.h
CATFILES	= comsat.cat
HFILES		= ${MSGHDRS}

ILIST		= comsat
IDIR		= /usr/sbin/

CFLAGS		= -D_BSD -DAIX -DVMUNIX -DV7 -DBSD_INCLUDES -DNOCATMACRO

.include <${RULES_MK}>
