# @(#)17	1.1  src/rspc/usr/lib/boot/mkmboot/Makefile, rspccfg, rspc411, GOLD410 4/28/94 18:20:04
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS        = mkmboot

OFILES		= mkmboot.o

ILIST           = mkmboot
IDIR            = /usr/lib/boot/

LIBS            =

.include <${RULES_MK}>

