# @(#)00	1.2  src/msg/bos/ja_JP/Makefile, bosmsg, msg411, GOLD410 2/9/94 15:04:22
#
# COMPONENT_NAME: bosmsg
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential	Restricted when
# combined with	the aggregated modules for this	product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT	International Business Machines	Corp. 1994
# All Rights Reserved
#
# US Government	Users Restricted Rights	- Use, duplication or
# disclosure restricted	by GSA ADP Schedule Contract with IBM Corp.
#

MSGLANG	= ja_JP
SOURCE_CODESET = IBM-932
TARGET_CODESET = IBM-eucJP

VPATH	= ${MAKETOP}/msg/bos/Ja_JP:${MAKETOP}/msg/bos/base

.include <${MAKETOP}/msg/bos/Ja_JP/bosmsg.mk.ibmstub>
